import type { Exercise } from "../types";

// Exercise library (spec §14). Future equipment exercises are seeded with
// isAvailable: false so the app supports them later without redesign (spec §2).

export const EXERCISES: Exercise[] = [
  // ---------- Skill ----------
  {
    id: "handstand",
    name: "Handstand",
    category: "SKILL",
    equipment: ["BODYWEIGHT"],
    isAvailable: true,
    defaultGrip: "BODYWEIGHT",
    purpose: ["balance", "shoulder stability", "body control", "enjoyment"],
    watchFor: [
      "Push tall through shoulders",
      "Brace abs",
      "Squeeze glutes",
      "Keep body tight",
      "Controlled exits",
      "Stop before technique deteriorates",
    ],
  },

  // ---------- Ballistic / Power ----------
  {
    id: "kb-swing",
    name: "Two-hand Kettlebell Swing",
    category: "BALLISTIC",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    aliases: ["swing", "kettlebell swing", "kb swing"],
    defaultGrip: "HANDLE",
    purpose: ["hip power", "posterior chain", "conditioning", "grip"],
    watchFor: [
      "Hip-driven, not arm-lifted",
      "Neutral spine",
      "Bell driven by hips",
      "Arms guide rather than lift",
      "Stop if technique deteriorates",
    ],
    commonMistakes: ["Squatting the swing", "Rounding the low back", "Lifting with shoulders"],
  },
  {
    id: "ballistic-row",
    name: "Ballistic Row",
    category: "BALLISTIC",
    equipment: ["KETTLEBELL"],
    isAvailable: true, // equipment-ready; programmed from Weeks 2–3 (spec §15)
    defaultGrip: "HANDLE",
    purpose: ["explosive pulling", "back", "biceps", "grip", "athletic power"],
    watchFor: ["Explosive pull, controlled lowering", "Square hips", "Neutral spine"],
  },

  // ---------- Squat / Legs ----------
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    category: "SQUAT_LEGS",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    defaultGrip: "HORNS",
    purpose: ["legs", "glutes", "trunk", "squat pattern"],
    watchFor: ["Controlled descent", "Brace", "Knees track naturally", "Keep bell close"],
    commonMistakes: ["Heels lifting", "Collapsing chest", "Bell drifting away from body"],
  },
  {
    id: "slow-goblet-squat",
    name: "Slow Goblet Squat",
    category: "SQUAT_LEGS",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    defaultGrip: "HORNS",
    purpose: ["hypertrophy", "control", "legs", "trunk"],
    watchFor: ["Controlled descent", "Brace", "Knees track naturally", "Keep bell close"],
  },
  {
    id: "front-rack-reverse-lunge",
    name: "Front-rack Reverse Lunge",
    category: "SQUAT_LEGS",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    defaultGrip: "HANDLE",
    purpose: ["legs", "glutes", "core", "anti-rotation"],
    watchFor: [
      "Tall torso",
      "Controlled descent",
      "Front foot planted",
      "Resist rotation from offset bell",
    ],
  },
  {
    id: "deep-squat-curl",
    name: "Deep Squat Curl",
    category: "GRIP_ARMS",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    defaultGrip: "HORNS",
    purpose: ["biceps", "forearms", "grip", "hips", "squat position", "posture", "trunk"],
    watchFor: [
      "Stable squat",
      "Chest controlled",
      "Do not bounce",
      "Curl deliberately",
      "Stop if low-back position becomes poor",
    ],
  },

  // ---------- Hinge ----------
  {
    id: "single-leg-rdl",
    name: "Single-leg RDL",
    category: "HINGE",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    aliases: ["rdl", "romanian deadlift", "single leg deadlift"],
    defaultGrip: "HANDLE",
    purpose: ["hamstrings", "glutes", "balance", "hip hinge"],
    watchFor: ["Square hips", "Long spine", "Hip hinge", "Resist rotation"],
  },

  // ---------- Pull ----------
  {
    id: "one-arm-row",
    name: "One-arm Row",
    category: "PULL",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    aliases: ["row", "single arm row", "kb row"],
    defaultGrip: "HANDLE",
    purpose: ["lats", "upper back", "biceps", "grip"],
    watchFor: [
      "Do not rotate torso",
      "Pull elbow toward hip",
      "Control lowering",
      "Keep shoulder away from ear",
    ],
  },
  {
    id: "gorilla-row",
    name: "Gorilla Row",
    category: "PULL",
    equipment: ["DOUBLE_KETTLEBELL"],
    isAvailable: false, // requires two suitable kettlebells (spec §15)
    defaultGrip: "HANDLE",
    purpose: ["back", "grip", "hinge endurance"],
    watchFor: ["Flat back", "Row without torso rotation"],
  },
  {
    id: "renegade-row-push-up",
    name: "Renegade Row + Push-up",
    category: "PULL",
    equipment: ["DOUBLE_KETTLEBELL"],
    isAvailable: false, // works best with two stable bells (spec §15)
    defaultGrip: "HANDLE",
    purpose: ["chest", "back", "anti-rotation", "trunk stabilization"],
    watchFor: ["Hips square", "No rocking", "Controlled row"],
  },

  // ---------- Push ----------
  {
    id: "strict-press",
    name: "Strict Press",
    category: "PUSH",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    defaultGrip: "HANDLE",
    purpose: ["shoulders", "triceps", "overhead strength"],
    watchFor: ["Brace before press", "Neutral wrist", "Do not lean sideways", "Controlled lockout"],
  },
  {
    id: "clean-strict-press",
    name: "Clean + Strict Press",
    category: "PUSH",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    aliases: ["clean and press", "clean & press", "clean press", "c&p", "cp"],
    defaultGrip: "HANDLE",
    purpose: ["shoulders", "triceps", "upper body strength", "trunk stabilization"],
    watchFor: [
      "Smooth clean",
      "Stable rack",
      "Neutral wrist",
      "Brace before press",
      "Do not lean sideways",
      "Controlled lockout",
    ],
    commonMistakes: ["Banging the forearm on the clean", "Pressing before bracing", "Side lean"],
  },
  {
    id: "floor-press",
    name: "Floor Press",
    category: "PUSH",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    defaultGrip: "HANDLE",
    purpose: ["chest", "triceps", "shoulder-safe pressing"],
    watchFor: ["Controlled shoulder", "Forearm vertical", "Brace torso", "Slow lowering"],
  },
  {
    id: "push-up",
    name: "Push-up",
    category: "PUSH",
    equipment: ["BODYWEIGHT"],
    isAvailable: true,
    aliases: ["pushup", "press up"],
    defaultGrip: "BODYWEIGHT",
    purpose: ["chest", "triceps", "trunk"],
    watchFor: ["Rigid plank body", "Full range", "Elbows ~45°", "Stop before form breaks"],
  },
  {
    id: "ring-dip",
    name: "Ring Dip",
    category: "PUSH",
    equipment: ["RINGS"],
    isAvailable: false, // rings ordered, not installed (spec §2)
    defaultGrip: "NONE",
    purpose: ["chest", "triceps", "shoulders", "hypertrophy"],
    watchFor: ["Stable turnout", "Controlled depth"],
  },
  {
    id: "ring-push-up",
    name: "Ring Push-up",
    category: "PUSH",
    equipment: ["RINGS"],
    isAvailable: false,
    defaultGrip: "NONE",
    purpose: ["chest", "stabilization", "hypertrophy"],
    watchFor: ["Rings steady", "Body rigid"],
  },

  // ---------- Core / Rotation / Stability ----------
  {
    id: "halo",
    name: "Halo",
    category: "CORE",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    defaultGrip: "HORNS",
    purpose: ["shoulders", "trunk control", "mobility", "grip"],
    watchFor: [
      "Move bell around head rather than simply above it",
      "Keep ribs controlled",
      "Move slowly",
      "Do not force shoulder range",
      "Keep grip deliberate",
    ],
  },
  {
    id: "around-the-world",
    name: "Around the World",
    category: "CORE",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    defaultGrip: "HANDLE",
    purpose: ["trunk control", "grip", "coordination"],
    watchFor: [
      "Smooth hand transfer",
      "Tall posture",
      "Do not wildly rotate torso",
      "Control the bell",
    ],
  },
  {
    id: "figure-8",
    name: "Figure 8",
    category: "CORE",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    aliases: ["figure eight"],
    defaultGrip: "HANDLE",
    purpose: ["coordination", "grip", "hip stability"],
    watchFor: ["Controlled hand exchange", "Hips stay stable", "Do not rush"],
  },
  {
    id: "low-windmill",
    name: "Low Windmill",
    category: "CORE",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    defaultGrip: "HANDLE",
    purpose: ["rotation", "hamstrings", "trunk control"],
    watchFor: [
      "Hinge rather than collapse",
      "Long spine",
      "Controlled rotation",
      "Move only through comfortable range",
    ],
  },
  {
    id: "suitcase-carry",
    name: "Suitcase Carry",
    category: "CORE",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    defaultGrip: "HANDLE",
    purpose: ["forearms", "grip", "obliques", "anti-side-bending", "posture"],
    watchFor: ["Stand tall", "No leaning", "Brace abs", "Walk deliberately", "Grip hard"],
  },
  {
    id: "rack-march",
    name: "Rack March",
    category: "CORE",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    defaultGrip: "HANDLE",
    purpose: ["anti-rotation", "trunk", "shoulder stability"],
    watchFor: ["No leaning", "Slow knee lift", "Hard abdominal brace", "Stable rack"],
  },
  {
    id: "north-south-plank-drag",
    name: "North-South Plank Drag",
    category: "CORE",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    aliases: ["plank drag", "kb drag"],
    defaultGrip: "HANDLE",
    purpose: ["anti-rotation", "abs", "shoulders", "chest stabilization"],
    watchFor: [
      "Keep hips square",
      "Do not rock side to side",
      "Drag under control",
      "Brace before each pull",
    ],
  },
  {
    id: "plank-kb-drag",
    name: "Plank Kettlebell Drag",
    category: "CORE",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    defaultGrip: "HANDLE",
    purpose: ["anti-rotation", "abs", "shoulder stability"],
    watchFor: ["Hips square", "Controlled drag"],
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    category: "CORE",
    equipment: ["BODYWEIGHT"],
    isAvailable: true,
    defaultGrip: "BODYWEIGHT",
    purpose: ["core stabilization", "rib control"],
    watchFor: ["Low back gently pressed down", "Slow opposite arm/leg", "Breathe"],
  },
  {
    id: "hollow-hold",
    name: "Hollow Hold",
    category: "CORE",
    equipment: ["BODYWEIGHT"],
    isAvailable: true,
    defaultGrip: "BODYWEIGHT",
    purpose: ["core stabilization", "handstand carryover"],
    watchFor: ["Low back pressed to floor", "Ribs down", "Stop when shaking breaks position"],
  },
  {
    id: "side-plank",
    name: "Side Plank",
    category: "CORE",
    equipment: ["BODYWEIGHT"],
    isAvailable: true,
    defaultGrip: "BODYWEIGHT",
    purpose: ["obliques", "lateral trunk stability"],
    watchFor: ["Straight line head to feet", "Hips high", "Shoulder stacked"],
  },
  {
    id: "kb-gravedigger",
    name: "Kettlebell Gravedigger",
    category: "CORE",
    equipment: ["KETTLEBELL"],
    isAvailable: true, // equipment-ready; programmed later once rotational patterns are solid (spec §15)
    defaultGrip: "HANDLE",
    purpose: ["diagonal/rotational strength"],
    watchFor: ["Controlled diagonal path", "Brace throughout"],
  },

  // ---------- Grip / Arms ----------
  {
    id: "horn-curl",
    name: "Horn Curl",
    category: "GRIP_ARMS",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    defaultGrip: "HORNS",
    purpose: ["biceps", "brachialis", "forearms", "grip"],
    watchFor: [
      "Keep elbows mostly fixed",
      "Do not swing body",
      "Controlled lowering",
      "Squeeze deliberately at top",
    ],
  },
  {
    id: "bottom-up-hold",
    name: "Bottom-up Hold",
    category: "GRIP_ARMS",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    defaultGrip: "BOTTOM_UP_HANDLE",
    purpose: ["forearms", "grip", "wrist stability", "shoulder stabilization"],
    watchFor: [
      "Crush the handle",
      "Neutral wrist",
      "Stable shoulder",
      "Bell balanced vertically",
      "Stop before control is lost",
    ],
  },
  {
    id: "ball-squeeze-hold",
    name: "Ball Squeeze Hold",
    category: "GRIP_ARMS",
    equipment: ["KETTLEBELL"],
    isAvailable: true,
    defaultGrip: "BALL",
    purpose: ["forearms", "hand strength", "crush grip"],
    watchFor: [
      "Cup/grip bell body securely",
      "Keep bell close to torso",
      "Static controlled hold",
      "Do NOT use this grip for ballistic work",
    ],
  },

  // ---------- Conditioning ----------
  {
    id: "jump-rope",
    name: "Jump Rope",
    category: "CONDITIONING",
    equipment: ["JUMP_ROPE"],
    isAvailable: true,
    defaultGrip: "NONE",
    purpose: ["conditioning", "footwork", "calves"],
    watchFor: ["Relaxed shoulders", "Small hops", "Wrists spin the rope"],
  },

  // ---------- Future: bar / rings ----------
  {
    id: "pull-up",
    name: "Pull-up",
    category: "PULL",
    equipment: ["PULLUP_BAR"],
    isAvailable: false, // bar ordered, not installed (spec §2)
    defaultGrip: "NONE",
    purpose: ["lats", "back", "biceps", "grip"],
    watchFor: ["Full hang to chin over bar", "No kipping (strict)"],
  },
  {
    id: "chin-up",
    name: "Chin-up",
    category: "PULL",
    equipment: ["PULLUP_BAR"],
    isAvailable: false,
    defaultGrip: "NONE",
    purpose: ["biceps", "lats", "grip"],
    watchFor: ["Full range", "Controlled lowering"],
  },
  {
    id: "muscle-up",
    name: "Muscle-up",
    category: "PULL",
    equipment: ["PULLUP_BAR", "RINGS"],
    isAvailable: false,
    defaultGrip: "NONE",
    purpose: ["pull-to-push transition", "upper body power"],
    watchFor: ["Earn it after strict pull-ups and dips"],
  },
  {
    id: "ring-row",
    name: "Ring Row",
    category: "PULL",
    equipment: ["RINGS"],
    isAvailable: false,
    defaultGrip: "NONE",
    purpose: ["back", "scapular control"],
    watchFor: ["Rigid body line", "Full squeeze at top"],
  },
];

export const EXERCISES_BY_ID: Record<string, Exercise> = Object.fromEntries(
  EXERCISES.map((e) => [e.id, e]),
);

export function getExercise(id: string): Exercise {
  const ex = EXERCISES_BY_ID[id];
  if (!ex) throw new Error(`Unknown exercise id: ${id}`);
  return ex;
}
