import type { Equipment, SkillFamily, SkillVariation } from "../types";

// Calisthenics skill-progression library.
//
// Progression definitions are REUSABLE and effectively IMMUTABLE: workout
// session snapshots and skill-practice history reference variations by id.
// Never delete or renumber a variation once shipped — append new variations
// (new ids, new levels at the end) instead, so old sessions keep resolving.
//
// Levels within a family are strictly ordered integers starting at 1, no gaps.

const BODYWEIGHT_ONLY: Equipment[] = ["BODYWEIGHT"];
const RINGS_ONLY: Equipment[] = ["RINGS"];
const BAR_ONLY: Equipment[] = ["PULLUP_BAR"];

export const SKILL_FAMILIES: SkillFamily[] = [
  // ---------------------------------------------------------------- handstand
  {
    id: "handstand-control",
    name: "Handstand Control",
    category: "HANDSTAND",
    isAvailable: true,
    variations: [
      {
        id: "handstand-wall-facing-hold",
        level: 1,
        name: "Wall-Facing Handstand Hold",
        shortCue: "Chest-to-wall handstand: toes on the wall, body stacked and tight.",
        instructions: [
          "Start on hands and feet with your feet against the base of a wall, hands roughly shoulder-width.",
          "Walk your feet up the wall while walking your hands in toward it, until your chest faces the wall and only your toes touch it.",
          "Stack wrists, shoulders and hips in one line; push tall through the shoulders and point the toes.",
          "Hold the position, breathing steadily. A good hold is one where the body stays in a straight line with locked elbows.",
          "Walk back down under control the same way you came up — no collapsing out.",
        ],
        tips: [
          "Spread the fingers and grip the floor.",
          "Squeeze the glutes and ribs down to avoid a banana back.",
        ],
        stopWhen: "Stop the set when the elbows bend, shoulders sink, or the lower back arches hard.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 4, holdSec: 20 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when you hold 30 s clean, close to the wall, across all sets.",
      },
      {
        id: "handstand-wall-shifts",
        level: 2,
        name: "Wall Handstand Weight Shifts",
        shortCue: "In a chest-to-wall handstand, rock your weight from hand to hand without lifting them.",
        instructions: [
          "Set up a chest-to-wall handstand as in the wall-facing hold, toes lightly on the wall.",
          "Slowly lean your weight over one hand until the other hand feels almost unloaded — but keep it on the floor.",
          "Shift back through center to the other side in a slow, controlled rhythm.",
          "One rep = one full shift to a side with the free hand nearly weightless and no wobble through the hips.",
          "Come down under control before quality drops.",
        ],
        tips: [
          "Shift from the shoulders, not by bending the elbows.",
          "Keep the hips quiet — the movement is small and slow.",
        ],
        stopWhen: "Stop the set when shifts get jerky or you have to step the hands to save balance.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 6, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when the unloaded hand could visibly lift on every rep of every set.",
      },
      {
        id: "handstand-wall-shoulder-taps",
        level: 3,
        name: "Wall Handstand Shoulder Taps",
        shortCue: "Chest-to-wall handstand; lift a hand and tap its own shoulder.",
        instructions: [
          "Set up a chest-to-wall handstand with toes lightly on the wall.",
          "Shift your weight fully over one hand, lift the other hand off the floor and tap that hand to its own shoulder.",
          "Replace the hand quietly and shift to the other side.",
          "One rep = one tap with the supporting arm locked and hips level; alternate sides.",
        ],
        tips: [
          "Slow is strong: a one-second tap beats a fast slap.",
          "Push extra tall through the supporting shoulder before lifting the hand.",
        ],
        stopWhen: "Stop the set when you start falling out sideways or the taps become rushed slaps.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 8, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when you tap slowly and quietly for full sets, barely using the wall.",
      },
      {
        id: "handstand-freestanding-hold",
        level: 4,
        name: "Freestanding Handstand Hold",
        shortCue: "Kick up to a handstand in open space and balance.",
        instructions: [
          "Stand in a lunge with arms overhead, hands ready to plant shoulder-width in open space (soft surface or spotter nearby if needed).",
          "Plant the hands, kick one leg up followed by the other, and bring the body into a stacked line: wrists, shoulders, hips, ankles.",
          "Balance using fingertip and wrist pressure — press the fingertips down when falling over, press the heel of the hand when falling back.",
          "A good attempt is any hold of roughly 3 seconds or more with legs together and body tight.",
          "Exit by stepping down one leg at a time or cartwheeling out — always under control.",
        ],
        tips: [
          "Look at the floor between the hands, not forward.",
          "Small kicks: it is easier to add a bit more kick than to save an overshoot.",
        ],
        prescriptionType: "ATTEMPTS",
        defaultPrescription: { sets: 1, attempts: 8 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when most attempts hold 10 s or more with a quiet body line.",
      },
      {
        id: "handstand-free-shifts",
        level: 5,
        name: "Freestanding Shifts & Controlled Steps",
        shortCue: "In a freestanding handstand, shift weight hand to hand and take single deliberate steps.",
        instructions: [
          "Kick up to a freestanding handstand and find your balance for a breath or two.",
          "Slowly shift your weight over one hand, then the other, keeping the hips stacked over the shoulders.",
          "When a shift feels stable, lift the unloaded hand slightly and replace it a few centimetres away — one deliberate step.",
          "A good attempt contains at least two controlled shifts or steps before coming down; falling out immediately does not count.",
        ],
        tips: [
          "Move the hand, not the whole body — the lean comes first, the step follows.",
          "Keep the legs glued together to stop the hips twisting.",
        ],
        stopWhen: "Stop the session's balance work when attempts get shorter instead of longer — fatigue kills balance practice.",
        prescriptionType: "ATTEMPTS",
        defaultPrescription: { sets: 1, attempts: 6 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when you can take 4+ small steps in a row without losing the line.",
      },
      {
        id: "handstand-walk-short",
        level: 6,
        name: "Short Handstand Walks (3–5 m)",
        shortCue: "Walk on your hands for a few metres in a straight line.",
        instructions: [
          "Mark a lane of 3–5 metres of clear, flat floor.",
          "Kick up to a handstand with a slight lean in the direction of travel.",
          "Take small, quick-but-controlled hand steps, keeping the hips stacked and the legs slightly ahead of the shoulders to maintain forward drift.",
          "A good attempt covers the full 3–5 m without sprinting, collapsing, or big banana-back arching; step down calmly at the end.",
        ],
        tips: [
          "Small steps — overstriding is the main cause of face-plants.",
          "Keep the elbows locked; bending an arm mid-walk is a collapse, not a step.",
        ],
        stopWhen: "Stop the set when steps turn into a frantic stumble or the elbows start bending.",
        prescriptionType: "ATTEMPTS",
        defaultPrescription: { sets: 1, attempts: 6 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when 5 m walks are consistent and finish with a controlled step-down.",
      },
      {
        id: "handstand-walk",
        level: 7,
        name: "Handstand Walking (10 m+, Turns)",
        shortCue: "Walk 10 m or more on your hands, including gentle direction changes.",
        instructions: [
          "Set a course of at least 10 metres, ideally with room to curve or turn.",
          "Kick up and walk with small controlled steps, breathing throughout — holding your breath ends walks early.",
          "To turn, take slightly larger steps with the outside hand and pivot gradually on the inside hand over several steps.",
          "A good attempt covers 10 m+ or includes a clean 90°+ turn, ending in a controlled step-down rather than a bail.",
        ],
        tips: [
          "Pick a spot a hand-length ahead on the floor and walk to it, then pick the next.",
          "Slow the cadence down when you feel balance drifting — speed hides problems it doesn't fix.",
        ],
        stopWhen: "Stop the set when wrists or shoulders complain or step quality visibly degrades.",
        prescriptionType: "ATTEMPTS",
        defaultPrescription: { sets: 1, attempts: 5 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when 10 m with a turn is routine and you rarely bail mid-walk.",
      },
      {
        id: "handstand-walk-advanced",
        level: 8,
        name: "Advanced Handstand Control",
        shortCue: "Walk, stop and hold mid-walk, pirouette, change direction — on demand.",
        instructions: [
          "Plan a small sequence before kicking up, e.g. walk 5 m → stop and hold 3 s → quarter pirouette → walk back.",
          "Kick up and execute the sequence, treating each element as its own skill: finish the stop fully before starting the turn.",
          "For a pirouette, shift all weight over one hand and step the other hand across, rotating the shoulders and hips together in 2–3 steps.",
          "A good attempt completes the planned sequence with deliberate pauses — a continuous stumble through the elements does not count.",
        ],
        tips: [
          "The stop-and-hold is the hard part: kill all momentum with the fingertips before moving again.",
          "Keep sequences short; quality over choreography length.",
        ],
        stopWhen: "Stop the set when you can no longer hold a genuine 2–3 s pause mid-walk.",
        prescriptionType: "ATTEMPTS",
        defaultPrescription: { sets: 1, attempts: 5 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "This is the top of the family — keep expanding sequence difficulty at your own pace.",
      },
    ],
  },

  // -------------------------------------------------------------------- l-sit
  {
    id: "l-sit",
    name: "L-Sit",
    category: "STATIC_HOLD",
    isAvailable: true,
    variations: [
      {
        id: "l-sit-support-hold",
        level: 1,
        name: "Support Hold",
        shortCue: "Arms locked, body lifted between two supports or on the floor, feet resting or lightly touching.",
        instructions: [
          "Place your hands on two sturdy parallel surfaces (chairs, boxes, parallettes) or flat on the floor beside your hips while seated with legs extended.",
          "Press down hard, lock the elbows and push the shoulders down away from the ears, lifting your hips.",
          "On raised surfaces let the feet hang; on the floor keep heels lightly touching while taking maximum weight into the hands.",
          "A good hold keeps the elbows locked and shoulders depressed for the full time.",
        ],
        tips: [
          "Think 'push the world away' — the higher you press, the easier it feels.",
          "Keep the chest proud, not slumped between the shoulders.",
        ],
        stopWhen: "Stop the set when the shoulders shrug up to the ears or the elbows soften.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 4, holdSec: 20 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when you hold 30 s with locked arms and calm breathing across all sets.",
      },
      {
        id: "l-sit-tuck-support",
        level: 2,
        name: "Tuck Support (Knees Up)",
        shortCue: "Support hold with knees pulled up toward the chest, feet fully off the floor.",
        instructions: [
          "Set up a support hold on parallettes, boxes or the floor.",
          "Press tall, then pull both knees up toward your chest so the feet clear the floor completely.",
          "Keep the elbows locked and the hips roughly level with or slightly behind the hands.",
          "A good hold = feet off the floor the whole time with no elbow bend; the moment a foot touches down, the hold is over.",
        ],
        tips: [
          "Round the upper back slightly and brace the abs hard — this is a compression exercise, not just an arm exercise.",
          "Exhale steadily; breath-holding shortens the set.",
        ],
        stopWhen: "Stop the set when the feet drop or the shoulders shrug to the ears.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 4, holdSec: 15 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when 20 s tuck supports feel routine across all sets.",
      },
      {
        id: "l-sit-tuck",
        level: 3,
        name: "Tuck L-Sit (Shins Parallel)",
        shortCue: "Tuck support with the knees lifted until the shins are parallel to the floor.",
        instructions: [
          "Set up a tuck support with feet off the floor, arms locked.",
          "Lift the knees higher until your thighs are near horizontal and your shins are parallel to the floor, knees together.",
          "Hold this position — hips slightly behind the hands, abs crushed tight, shoulders pressed down.",
          "A good hold keeps the shins parallel to the floor; if the knees sink below hip height, the rep no longer counts.",
        ],
        tips: [
          "Push the floor down and pull the knees up at the same time — the two actions balance each other.",
          "Keep the toes pointed; it tightens the whole leg line.",
        ],
        stopWhen: "Stop the set when the knees sag below parallel or the arms start to bend.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 4, holdSec: 12 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when you hold 15 s with shins parallel across all sets.",
      },
      {
        id: "l-sit-one-leg",
        level: 4,
        name: "One-Leg L-Sit",
        shortCue: "Tuck L-sit with one leg fully extended, the other still tucked.",
        instructions: [
          "Start in a solid tuck L-sit, shins parallel.",
          "Extend one leg straight out in front until the knee locks, keeping that leg at or above hip height.",
          "Keep the other knee tucked and the arms locked; the hips must not sink.",
          "A good hold keeps the extended knee locked and the foot at hip height or higher for the full time. Work both sides.",
        ],
        tips: [
          "Point the toe of the extended leg and push it long — a bent 'almost straight' knee doesn't count.",
          "Lean the shoulders slightly forward to counterweight the extended leg.",
        ],
        stopWhen: "Stop the set when the extended leg drops below hip height or the knee bends.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 3, holdSec: 10, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when 12 s per side is clean, with the extended knee genuinely locked.",
      },
      {
        id: "l-sit-alternating",
        level: 5,
        name: "Alternating Leg Extensions",
        shortCue: "In a tuck L-sit, extend and retract one leg at a time in a slow rhythm.",
        instructions: [
          "Start in a tuck L-sit with shins parallel and arms locked.",
          "Slowly extend one leg to a full lockout, hold it for one second, then retuck it.",
          "Extend the other leg the same way; keep the hips still and the shoulders pressed down throughout.",
          "One rep = one full extend-hold-retuck per leg with no touchdown and no hip drop between reps.",
        ],
        tips: [
          "Move only the leg — if the torso pumps up and down, slow down.",
          "Exhale on each extension to keep the abs engaged.",
        ],
        stopWhen: "Stop the set when the feet start brushing the floor between reps.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 6, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when all reps lock out fully at hip height without the hold collapsing.",
      },
      {
        id: "l-sit-advanced-tuck",
        level: 6,
        name: "Advanced Tuck (Legs at 45°)",
        shortCue: "Both legs extended together but angled about 45° below horizontal — the bridge to the full L.",
        instructions: [
          "Set up a support hold, arms locked, shoulders down.",
          "Extend both legs together with knees locked, letting them sit at roughly 45° below horizontal (feet clearly off the floor, below hip height).",
          "Keep the knees squeezed together, toes pointed, abs braced.",
          "A good hold keeps both knees locked and feet off the floor for the full time — the angle may be low, but the knees may not bend.",
        ],
        tips: [
          "Fight for a little more height every session; the last 45° is pure compression strength.",
          "Push the hands down harder as the legs fatigue — the arms buy the abs time.",
        ],
        stopWhen: "Stop the set when the knees bend or the heels touch down.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 3, holdSec: 10 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when the legs creep close to horizontal for most of a 10 s hold.",
      },
      {
        id: "l-sit-full-short",
        level: 7,
        name: "Full L-Sit (Short Holds)",
        shortCue: "The real thing: legs straight and horizontal — in short, honest doses.",
        instructions: [
          "Set up a support hold on parallettes or the floor, arms locked, shoulders down.",
          "Lift both legs together until they are straight and parallel to the floor, forming an 'L' with your torso.",
          "Hold for a short, strict count — knees locked, toes pointed, feet at hip height.",
          "A good hold is 5–10 s at genuinely horizontal; a sagging 15 s hold is worth less than a strict 5 s one.",
        ],
        tips: [
          "Accumulate quality: many short strict holds beat one long ugly one.",
          "Lean the shoulders a touch forward of the hands to balance the legs.",
        ],
        stopWhen: "Stop the set the moment the feet drop below hip height — don't grind out a sagging hold.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 4, holdSec: 6 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when 10 s strict holds are repeatable across all sets.",
      },
      {
        id: "l-sit-full",
        level: 8,
        name: "Full L-Sit (15 s+)",
        shortCue: "Strict full L-sit held for 15 seconds or more.",
        instructions: [
          "Set up exactly as for the short full L-sit: arms locked, shoulders down, legs straight and horizontal.",
          "Hold the strict position while breathing in short, controlled breaths — do not hold your breath for 15 s.",
          "Keep checking the line: knees locked, toes pointed, feet at hip height, shoulders away from ears.",
          "A good hold maintains the strict L for the full prescribed time with no visible sag.",
        ],
        tips: [
          "Set a timer or count out loud — perceived time in an L-sit is wildly inflated.",
          "Grip the parallettes or floor hard; hand pressure feeds shoulder stability.",
        ],
        stopWhen: "Stop the set when the legs sag or the shoulders shrug — end on a strict position.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 3, holdSec: 15 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up to V-sit work when 20 s strict L-sits are consistent.",
      },
      {
        id: "l-sit-v-sit",
        level: 9,
        name: "V-Sit Progression",
        shortCue: "Lift the legs above horizontal, tilting the torso back — higher compression than the L.",
        instructions: [
          "Start in a strict full L-sit on parallettes (they give more room than the floor).",
          "Keeping the knees locked, lift the feet above hip height while letting the torso lean slightly back and the hips shift forward.",
          "Aim the toes toward your face; the higher the legs, the more the shoulders travel behind the hands.",
          "A good hold keeps the legs clearly above horizontal with locked knees for the full time — even a small angle above the L counts as progress.",
        ],
        tips: [
          "Train pike compression separately (seated leg lifts, pike stretches) — the V-sit is won on flexibility as much as strength.",
          "Raise the legs gradually over weeks; jumping straight to a deep V invites elbow strain.",
        ],
        stopWhen: "Stop the set when the knees bend or the legs fall back to horizontal.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 3, holdSec: 8 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Top of the family — keep raising the leg angle toward a true V over time.",
      },
    ],
  },

  // ------------------------------------------------------------- pistol squat
  {
    id: "pistol-squat",
    name: "Pistol Squat",
    category: "LEGS",
    isAvailable: true,
    variations: [
      {
        id: "pistol-assisted",
        level: 1,
        name: "Assisted Pistol Squat",
        shortCue: "One-leg squat holding a doorframe, post or strap for balance and help.",
        instructions: [
          "Stand on one leg next to a sturdy support (doorframe, pole, suspension strap) holding it with one or both hands.",
          "Extend the free leg straight out in front and squat down on the standing leg as deep as you can, using the hands as little as possible.",
          "Keep the standing heel flat on the floor and the chest up.",
          "Drive back up through the standing heel. A good rep reaches full depth (hip below knee) with the heel down, using the arms for balance more than for pulling.",
        ],
        tips: [
          "Pull with the hands only as much as needed — every session, try to use them less.",
          "Sit down between your standing hip and heel, not backward onto air.",
        ],
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 6, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when full-depth reps need only fingertip assistance.",
      },
      {
        id: "pistol-box",
        level: 2,
        name: "Box / Target Pistol",
        shortCue: "One-leg squat down to a box or bench, touch, and stand back up.",
        instructions: [
          "Stand on one leg in front of a box, bench or chair (start around knee height), other leg extended forward.",
          "Squat down under control until your glutes lightly touch the target — touch, don't sit and rest.",
          "Keep the standing heel flat, arms reaching forward as a counterweight.",
          "Drive straight back up without rocking or using momentum from the box. A good rep is a soft touch and an immediate stand-up.",
        ],
        tips: [
          "Lower the target over time — the box height is your progress meter.",
          "Reach the arms and free leg long in front; they are your balance pole.",
        ],
        stopWhen: "Stop the set when you start dropping onto the box instead of touching it.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 5, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when you control 5 clean reps per side to a target below knee height.",
      },
      {
        id: "pistol-counterbalance",
        level: 3,
        name: "Counterbalanced Pistol",
        shortCue: "Full-range pistol holding a light weight out in front as a counterweight.",
        instructions: [
          "Hold a light kettlebell or similar weight (4–12 kg) at chest height with both hands, arms extending forward as you descend.",
          "Stand on one leg, extend the other forward, and squat all the way down until the hamstring rests on the calf.",
          "Keep the heel flat and the extended leg off the floor throughout.",
          "Stand back up without the free foot touching down. A good rep is full depth, heel down, free leg clear of the floor the whole way.",
        ],
        tips: [
          "The weight goes forward as you go down — that's the whole trick.",
          "Use the lightest weight that lets you complete the rep; heavier is not the goal here.",
        ],
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 5, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when the counterweight feels ornamental — reduce it toward zero, then work eccentrics.",
      },
      {
        id: "pistol-eccentric",
        level: 4,
        name: "Controlled Eccentric Pistol",
        shortCue: "Unassisted slow lower to the bottom of a pistol; stand up however you need.",
        instructions: [
          "Stand on one leg with no support and no counterweight, free leg and arms reaching forward.",
          "Lower yourself over a slow 3–5 second count all the way to the bottom of the pistol.",
          "Keep the heel flat and the descent smooth — no free-fall in the last third.",
          "At the bottom, stand up any way you like (both legs, hands on floor, roll back). The rep is the lowering. A good rep is smooth and takes at least 3 seconds.",
        ],
        tips: [
          "Fight hardest in the bottom third — that's where pistols are lost.",
          "Film a rep occasionally; a 'slow' negative is often faster than it feels.",
        ],
        stopWhen: "Stop the set when you can no longer control the last third and drop into the bottom.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 4, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when every negative takes 4–5 s and ends in a quiet, balanced bottom position.",
      },
      {
        id: "pistol-full",
        level: 5,
        name: "Full Pistol Squat",
        shortCue: "Unassisted single-leg squat: all the way down, all the way up.",
        instructions: [
          "Stand on one leg, other leg extended straight in front, arms reaching forward for balance.",
          "Squat down under control until the hamstring meets the calf, heel flat the entire time.",
          "Keep the extended leg and free foot clear of the floor.",
          "Drive back up to a full stand without bouncing off the bottom. A good rep: full depth, flat heel, free leg airborne throughout, no hands.",
        ],
        tips: [
          "Grip the floor with the standing foot — a stable foot is a stable pistol.",
          "Exhale hard on the way up; it braces the trunk.",
        ],
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 4, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when 5 clean reps per side are routine on both legs.",
      },
      {
        id: "pistol-pause",
        level: 6,
        name: "Pause Pistol (2 s in the Hole)",
        shortCue: "Full pistol with a strict 2-second dead stop at the bottom.",
        instructions: [
          "Perform a full pistol descent to the very bottom position.",
          "Hold completely still for a genuine 2-second count — no rocking, no heel lift, free leg still airborne.",
          "Drive up to a full stand with zero bounce; the pause removes the stretch reflex on purpose.",
          "A good rep has a motionless pause and a smooth stand-up. If you bob or the free foot taps down, the rep doesn't count.",
        ],
        tips: [
          "Count the pause out loud — silent counts shrink under fatigue.",
          "Stay tall in the chest at the bottom; folding forward makes the stand-up harder.",
        ],
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 3, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when 3–4 paused reps per side stay motionless in the hole.",
      },
      {
        id: "pistol-elevated",
        level: 7,
        name: "Elevated / Advanced Single-Leg Squat",
        shortCue: "Pistols off an elevation (deficit) or with added load — the top of the family.",
        instructions: [
          "Stand on a stable elevation (low box, step, thick plate) so the free leg can drop below the level of the standing foot, or hold a kettlebell at the chest for loaded pistols.",
          "Perform a full pistol: controlled descent to full depth, heel flat, free leg clear.",
          "The elevation demands extra balance and mobility since the free leg no longer needs to stay horizontal; load demands extra strength.",
          "A good rep meets the same standard as a full pistol — full depth, no touchdown, no bounce.",
        ],
        tips: [
          "Master the deficit version before stacking load on top.",
          "Add load in small jumps (2–4 kg) held at the chest, goblet style.",
        ],
        stopWhen: "Stop the set when depth shortens or the heel starts lifting — quality defines this level.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 3, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Top of the family — progress by adding small load or deficit height over time.",
      },
    ],
  },

  // -------------------------------------------------------- handstand push-up
  {
    id: "handstand-push-up",
    name: "Handstand Push-Up",
    category: "HANDSTAND",
    isAvailable: true,
    variations: [
      {
        id: "hspu-pike",
        level: 1,
        name: "Pike Push-Up",
        shortCue: "Push-up in an A-frame position, pressing the head toward the floor between the hands.",
        instructions: [
          "Start in a push-up position, then walk the feet in and lift the hips high so your body forms an upside-down V.",
          "Hands shoulder-width, arms and legs as straight as possible, head between the arms.",
          "Bend the elbows and lower the top of your head toward the floor just in front of your hands.",
          "Press back up to straight arms. A good rep: head lightly touches (or nearly touches) the floor and the hips stay high the whole time.",
        ],
        tips: [
          "Elbows track back at roughly 45°, not flared straight out.",
          "The higher the hips, the more this becomes a shoulder press — keep pushing them up.",
        ],
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 8 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when 10 smooth reps to a light head-touch are easy.",
      },
      {
        id: "hspu-pike-elevated",
        level: 2,
        name: "Elevated Pike Push-Up",
        shortCue: "Pike push-up with feet on a box — more weight over the hands, more vertical press.",
        instructions: [
          "Place your feet on a sturdy box or bench (start around knee height) and walk the hands back until the hips stack over the shoulders as much as possible.",
          "Keep the arms straight, head between the arms, torso close to vertical.",
          "Lower the top of the head to the floor under control, elbows tracking back.",
          "Press back to locked arms. A good rep touches the head down softly with the hips staying stacked, not sagging toward a push-up.",
        ],
        tips: [
          "Raise the box over time to get more vertical — that is the progression inside this level.",
          "Put a folded towel under the head as a depth target and crash pad.",
        ],
        stopWhen: "Stop the set when the hips drift forward and reps turn into decline push-ups.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 6 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when 8 vertical reps from a high box are clean.",
      },
      {
        id: "hspu-wall-headstand-partial",
        level: 3,
        name: "Wall Headstand Push-Up (Partial)",
        shortCue: "Back-to-wall headstand; press partway up and lower back to the head.",
        instructions: [
          "Kick up to a handstand with your back to the wall, hands about 15–20 cm from it, on a padded surface for the head.",
          "Lower under control until the top of your head lightly touches the floor.",
          "Press back up through whatever range you can — even a few centimetres counts — then lower again with control.",
          "A good rep is a controlled lower to a soft head-touch plus a genuine press upward; measure progress by how much range you gain.",
        ],
        tips: [
          "Lower slowly — the eccentric builds the strength for the press.",
          "Keep the elbows tracking forward/45°, never flared level with the shoulders.",
        ],
        stopWhen: "Stop the set when you can no longer lower slowly and the head starts bumping the floor.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 5 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when your partial presses cover more than half the range on every rep.",
      },
      {
        id: "hspu-wall-headstand-full",
        level: 4,
        name: "Wall Headstand Push-Up (Full ROM)",
        shortCue: "From head on floor to locked arms and back, against the wall.",
        instructions: [
          "Set up in a back-to-wall handstand with padding under the head.",
          "Lower under full control until the head touches, then press all the way back to locked elbows.",
          "Keep the body tight and the heels lightly on the wall — no wild arching or kipping with the legs.",
          "A good rep goes head-touch to full lockout without the feet pushing off the wall.",
        ],
        tips: [
          "Squeeze the glutes at the sticking point — a loose body leaks pressing power.",
          "If you stall mid-press, fight for 2 s, then lower out safely; that grinding effort is productive.",
        ],
        stopWhen: "Stop the set one rep before failure — failing upside-down against a wall is not worth it.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 4 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when 5 full-range reps are smooth with no leg drive.",
      },
      {
        id: "hspu-wall-partial",
        level: 5,
        name: "Wall Handstand Push-Up (Partial, Head Free)",
        shortCue: "Wall handstand; lower toward the floor without resting the head, press back up.",
        instructions: [
          "Kick up to a back-to-wall handstand, hands slightly wider than shoulder-width.",
          "Lower under control as deep as you can while keeping the head OFF the floor — hovering, not resting.",
          "Press back to full lockout without pausing on the floor.",
          "A good rep hovers the head just above the floor (or to your current depth limit) and returns to lockout under control; track your depth over time.",
        ],
        tips: [
          "Place a small foam block under the head and shrink it as you get stronger — an honest depth gauge.",
          "The bottom few centimetres are the hardest strength jump in this family; expect slow progress and take it.",
        ],
        stopWhen: "Stop the set when depth visibly shrinks or you have to rest the head to get back up.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 3 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when you press from a light hover at the floor for all reps.",
      },
      {
        id: "hspu-wall",
        level: 6,
        name: "Wall Handstand Push-Up",
        shortCue: "Full-range handstand push-up against the wall: nose-to-floor, press to lockout.",
        instructions: [
          "Kick up to a back-to-wall handstand, body tight, heels lightly touching the wall.",
          "Lower under full control until the head lightly grazes the floor — touch, don't rest.",
          "Press straight back up to a full elbow lockout without leg drive or wall-kicking.",
          "A good rep: full depth, no rest at the bottom, full lockout at the top, body in one line throughout.",
        ],
        tips: [
          "Think 'push the floor away and look at it' — keeping the head neutral-ish protects the neck.",
          "Low, quality volume: 2–3 crisp reps beat 5 grinding ones.",
        ],
        stopWhen: "Stop the set one rep before failure, always.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 3 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Top of the family for now — build toward sets of 5, then consider freestanding work.",
      },
    ],
  },

  // ----------------------------------------------------- crow -> tuck planche
  {
    id: "crow-to-tuck-planche",
    name: "Crow to Tuck Planche",
    category: "PUSH",
    isAvailable: true,
    variations: [
      {
        id: "crow-frog-stand",
        level: 1,
        name: "Frog Stand",
        shortCue: "Squat down, knees resting on bent elbows, tip forward until the feet float.",
        instructions: [
          "Squat down and place your hands flat on the floor, shoulder-width, fingers spread.",
          "Bend the elbows slightly and nestle the inside of your knees onto the backs of your upper arms, near the elbows.",
          "Slowly shift your weight forward onto the hands until the feet lift off the floor.",
          "Balance there, looking at the floor slightly ahead of the hands. A good hold keeps both feet off the floor with the knees supported on the arms.",
        ],
        tips: [
          "Tip forward slowly — the balance point is closer than you fear.",
          "Put a pillow in front of you the first sessions; it removes the face-plant hesitation.",
        ],
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 4, holdSec: 15 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when relaxed 20 s frog stands are easy.",
      },
      {
        id: "crow-hold",
        level: 2,
        name: "Crow Stand (20 s+ Holds)",
        shortCue: "Frog stand refined: knees on the shelf of the arms, hips higher, longer holds.",
        instructions: [
          "Set up as for the frog stand: hands planted, knees on the upper arms.",
          "Lift the hips higher and pull the heels toward the glutes so the body is more compact.",
          "Balance using fingertip pressure; keep the gaze on the floor just ahead of the hands.",
          "A good hold is stone-still for the prescribed time — no toe-taps back to the floor.",
        ],
        tips: [
          "Squeeze the knees into the arms — active pressure is what stops wobble.",
          "Breathe; crows collapse when you brace-and-hold-breath.",
        ],
        stopWhen: "Stop the set when the wrists complain or you start toe-tapping to save balance.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 4, holdSec: 20 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when 25–30 s stone-still crows are routine.",
      },
      {
        id: "crow-straight-arm",
        level: 3,
        name: "Crow with Straighter Arms",
        shortCue: "Crow stand while progressively straightening the elbows — the planche lean starts here.",
        instructions: [
          "Set up in a solid crow stand.",
          "Gradually press the elbows toward straight while keeping the knees in contact with the arms (they slide toward the armpits as the arms straighten).",
          "Let the shoulders lean further forward past the wrists to keep the balance — straight arms demand more lean.",
          "A good hold keeps the elbows visibly straighter than a normal crow with the feet off the floor for the full time. Full lockout is the long-term goal, not the entry requirement.",
        ],
        tips: [
          "Straighten the arms a few degrees per week; this loads the biceps tendons and they adapt slowly.",
          "Push the floor away hard — protracted (rounded) shoulders are the strong position here.",
        ],
        stopWhen: "Stop the set at any sharp sensation in the inner elbow or wrist — tendon work has no heroics.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 3, holdSec: 12 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when near-straight-arm crows hold 15 s without elbow strain.",
      },
      {
        id: "crow-tuck-planche-attempts",
        level: 4,
        name: "Tuck Planche Attempts",
        shortCue: "From a lean, lift the knees off the arms — feet off, hips at hand height, nothing resting.",
        instructions: [
          "Place the hands on the floor or low parallettes, arms as straight as you can manage, shoulders leaning well past the wrists.",
          "Tuck the knees tightly to the chest and lift the feet, keeping the knees OFF the arms — nothing rests on anything.",
          "Aim to hold the hips at roughly hand/shoulder height with the back rounded.",
          "A good attempt gets both feet off the floor with knees unsupported, even for 1–2 seconds. Count every honest lift-off.",
        ],
        tips: [
          "Round the upper back hard (push the floor away) — a hollow back is the tuck planche's engine.",
          "Parallettes spare the wrists and are the recommended surface here.",
        ],
        stopWhen: "Stop the session's attempts when lift-offs stop happening — further grinding is just wrist wear.",
        prescriptionType: "ATTEMPTS",
        defaultPrescription: { sets: 1, attempts: 6 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when most attempts float for 2–3 s with the hips near hand height.",
      },
      {
        id: "crow-tuck-planche-hold",
        level: 5,
        name: "Tuck Planche Hold",
        shortCue: "Hold the tuck planche: knees to chest, hips level with shoulders, arms straight.",
        instructions: [
          "Set up on parallettes or the floor, lean the shoulders well past the hands and lift into the tuck: knees tight to the chest, feet up.",
          "Keep the arms as straight as possible and the upper back rounded, hips at shoulder height.",
          "Hold still, breathing in small sips.",
          "A good hold is 3 s+ motionless with nothing touching down; build the duration gradually.",
        ],
        tips: [
          "Depress and protract the shoulders — 'long arms, round back' is the whole cue.",
          "Short frequent exposure beats occasional max-outs for straight-arm strength.",
        ],
        stopWhen: "Stop the set when the hips drop below hand height or the elbows bend to save the hold.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 4, holdSec: 5 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Top of the family — extend hold time toward 10 s before chasing advanced tuck shapes.",
      },
    ],
  },

  // ------------------------------------------------------------- planche lean
  {
    id: "planche-lean",
    name: "Planche Lean",
    category: "PUSH",
    isAvailable: true,
    variations: [
      {
        id: "planche-lean-hold",
        level: 1,
        name: "Planche Lean",
        shortCue: "Push-up plank with the shoulders shifted forward past the hands.",
        instructions: [
          "Start in a strict push-up plank: hands under shoulders, arms locked, body in one line, toes on the floor.",
          "Keeping the arms locked, shift your whole body forward so the shoulders travel past the wrists.",
          "Round the upper back slightly (push the floor away), squeeze the glutes, and keep the hips in line — no sagging.",
          "Hold the leaned position. A good hold keeps the shoulders clearly in front of the wrists with locked elbows and a straight body.",
        ],
        tips: [
          "Turn the hands out 30–45° to spare the wrists.",
          "More toe-point = more lean; the calves control the depth.",
        ],
        stopWhen: "Stop the set when the hips sag or the elbows unlock.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 3, holdSec: 15 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when 20 s leans with shoulders past the wrists feel controlled.",
      },
      {
        id: "planche-lean-deep",
        level: 2,
        name: "Deep Planche Lean Holds",
        shortCue: "The same lean, pushed further — maximum forward shift you can hold with a straight body.",
        instructions: [
          "Set up a planche lean, then keep creeping the shoulders forward until you reach the deepest lean you can hold for the prescribed time.",
          "Rise onto the very tips of the toes; most of your weight should now be on the hands.",
          "Keep the elbows locked, upper back rounded, hips level.",
          "A good hold sits at (not beyond) your honest maximum lean, motionless, body straight. Mark your lean depth (e.g. where the shoulders sit over the floor) and push it session to session.",
        ],
        tips: [
          "Measure progress: film from the side or note how far past the wrists the shoulders travel.",
          "The forearms will lean forward visibly — that angle is exactly the strength you're building.",
        ],
        stopWhen: "Stop the set when the body pikes or the shoulders shake back to neutral.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 3, holdSec: 10 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when deep 12–15 s leans no longer feel like a fight.",
      },
      {
        id: "planche-lean-pseudo-push-up",
        level: 3,
        name: "Pseudo-Planche Push-Up",
        shortCue: "Push-ups performed while holding the forward lean — hands by the hips of the movement.",
        instructions: [
          "Set up a planche lean with hands turned out around waist/hip level relative to your torso, shoulders past the wrists.",
          "Keeping the forward lean, bend the elbows and lower the chest toward the floor.",
          "Press back to locked arms WITHOUT letting the shoulders drift back behind the wrists at the top.",
          "A good rep maintains the lean at both the top and bottom; if the shoulders retreat over the wrists, the rep no longer counts.",
        ],
        tips: [
          "Elbows track back along the ribs, not out.",
          "Shorter range with a real lean beats deep reps with no lean.",
        ],
        stopWhen: "Stop the set when you can no longer keep the shoulders in front of the wrists at the top of the rep.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 6 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when 8 leaned reps are clean with no lean loss at lockout.",
      },
      {
        id: "planche-lean-tuck-work",
        level: 4,
        name: "Tuck Planche Lean Work",
        shortCue: "Combine the lean with tucked knees — lean, tuck one leg or both, and fight for float.",
        instructions: [
          "Set up a deep planche lean on the floor or parallettes.",
          "Keeping maximum lean, draw one knee to the chest, balancing on the other toe; hold, then switch.",
          "When single-knee tucks are stable, pull both knees in and let the toes just barely drag or float off the floor.",
          "A good set maintains the deep lean throughout; any second of genuine two-foot float is a bonus, not a requirement.",
        ],
        tips: [
          "This bridges directly into tuck planche attempts — same shape, progressively less foot support.",
          "Keep the elbows locked at all costs; bend them and it becomes a different exercise.",
        ],
        stopWhen: "Stop the set when the lean shrinks back over the wrists — the lean IS the exercise.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 3, holdSec: 8 },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Top of the family — graduate into tuck planche attempts in the crow-to-tuck-planche line.",
      },
    ],
  },

  // ------------------------------------------------------------- shrimp squat
  {
    id: "shrimp-squat",
    name: "Shrimp Squat",
    category: "LEGS",
    isAvailable: true,
    variations: [
      {
        id: "shrimp-assisted",
        level: 1,
        name: "Assisted Shrimp Squat",
        shortCue: "One-leg squat with the rear foot held behind you, holding a support with one hand.",
        instructions: [
          "Stand on one leg and grab the other ankle behind you with the same-side hand, heel toward the glute (like a quad stretch).",
          "Hold a doorframe, pole or strap with the free hand for balance and light assistance.",
          "Squat down on the standing leg until the trailing knee lightly touches the floor beside/behind the standing heel.",
          "Drive back up through the standing foot. A good rep touches the knee down softly — no dropping — with the heel flat.",
        ],
        tips: [
          "Put a folded mat under the trailing knee while learning.",
          "Torso leans forward naturally — allow it, just keep the spine long.",
        ],
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 6, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when the assisting hand does almost nothing on every rep.",
      },
      {
        id: "shrimp-touch-down",
        level: 2,
        name: "Shrimp to Touch-Down",
        shortCue: "Unassisted shrimp: lower until the back knee kisses the floor, then stand.",
        instructions: [
          "Stand on one leg, holding the other ankle behind you; the free arm reaches forward for balance — no external support.",
          "Lower under control until the trailing knee touches the floor softly.",
          "Keep the standing heel flat and the touch silent — a thud means you fell the last part.",
          "Stand back up without letting go of the ankle. A good rep is a silent knee-touch and a controlled stand.",
        ],
        tips: [
          "Reach the free arm far forward on the descent — it's your counterweight.",
          "Control beats depth-speed: 3 seconds down is about right.",
        ],
        stopWhen: "Stop the set when knee-touches become audible landings.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 5, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when 6 silent-touch reps per side are consistent.",
      },
      {
        id: "shrimp-full",
        level: 3,
        name: "Full Shrimp Squat",
        shortCue: "Both hands hold the rear ankle; knee to floor and back up — the strict version.",
        instructions: [
          "Stand on one leg and hold the rear ankle with BOTH hands behind your back (this removes the counterbalancing arm).",
          "Lower under control until the trailing knee touches the floor.",
          "Keep the chest as upright as balance allows and the standing heel flat.",
          "Stand back up without releasing the ankle. A good rep keeps both hands on the ankle from start to finish.",
        ],
        tips: [
          "Expect a big balance jump from level 2 — slow the descent down even more.",
          "Grip the floor with the standing foot; the toes do real work here.",
        ],
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 4, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when 5 strict two-hand reps per side are smooth.",
      },
      {
        id: "shrimp-elevated",
        level: 4,
        name: "Elevated / Loaded Shrimp Squat",
        shortCue: "Full shrimp off an elevation for extra depth, or with a light vest/weight.",
        instructions: [
          "Stand on a stable elevation (low box or step) so the trailing knee must travel below the standing foot's level, or perform full shrimps wearing a light vest / holding the ankle with one hand and a light weight in the other.",
          "Lower under control until the trailing knee reaches its deepest point (below the platform for the elevated version).",
          "Keep the heel flat and the descent smooth.",
          "Stand back up under control. A good rep hits the full increased range without the knee crashing down.",
        ],
        tips: [
          "Add depth OR load, not both at once.",
          "Small elevations (5–10 cm) are plenty to start.",
        ],
        stopWhen: "Stop the set when the added range turns descents into drops.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 3, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Top of the family — progress load or elevation gradually over months.",
      },
    ],
  },

  // ------------------------------------------------------------- dragon squat
  {
    id: "dragon-squat",
    name: "Dragon Squat",
    category: "LEGS",
    isAvailable: true,
    variations: [
      {
        id: "dragon-assisted",
        level: 1,
        name: "Assisted Dragon Squat Pattern",
        shortCue: "Learn the wrap-around single-leg squat pattern while holding a solid support.",
        instructions: [
          "Stand on one leg holding a doorframe, pole or rings strap with one or both hands.",
          "Squat down on the standing leg while sweeping the free leg BEHIND and ACROSS the standing leg, knee pointing sideways — the legs wrap around each other.",
          "Descend as deep as your knees and hips allow, letting the standing heel stay flat and the torso rotate slightly toward the free-leg side.",
          "Stand back up along the same path. A good rep keeps the movement slow and pain-free; depth grows over weeks, not sets.",
        ],
        tips: [
          "This is a mobility puzzle first, strength exercise second — never force depth.",
          "Keep most of the assistance early on; reduce hand pressure gradually.",
        ],
        stopWhen: "Stop immediately at any knee pain — discomfort in the pattern means back off the depth.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 3, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when assisted full-depth wraps are comfortable and the hands barely help.",
      },
      {
        id: "dragon-partial",
        level: 2,
        name: "Partial Dragon Squat",
        shortCue: "Unassisted dragon squat to a comfortable partial depth.",
        instructions: [
          "Stand on one leg with no support, arms reaching forward for balance.",
          "Squat down while wrapping the free leg behind and across the standing leg, as learned in the assisted version.",
          "Descend only to a depth you can reverse under full control — half depth is a good rep at this level.",
          "Stand back up along the same wrapped path without touching the free foot down.",
        ],
        tips: [
          "Add a few centimetres of depth per week at most.",
          "Reaching both arms forward and slightly across helps counter the rotation.",
        ],
        stopWhen: "Stop the set when the free foot starts dabbing the floor or the knee complains.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 3, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when controlled reps reach near-full depth without assistance.",
      },
      {
        id: "dragon-full",
        level: 3,
        name: "Full Dragon Squat",
        shortCue: "The full wrap-around pistol: bottom position with legs crossed, stand back up.",
        instructions: [
          "Stand on one leg, no support, and lower into the full dragon squat: free leg wrapped behind and across, hips sinking to the standing calf.",
          "At the bottom, the free leg's thigh crosses over the standing shin, foot hovering off the floor.",
          "Pause briefly, keeping the standing heel flat.",
          "Stand back up along the same path with no touchdown. A good rep is slow, silent and pain-free — this is an advanced skill; tiny volumes, high quality.",
        ],
        tips: [
          "Treat every rep like a max attempt: full attention, full control.",
          "Keep the volume conservative permanently — this movement rewards patience and punishes greed.",
        ],
        stopWhen: "Stop the set at the first sign of knee strain or a rushed, falling descent.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 2, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Top of the family — polish smoothness and add a bottom pause before adding reps.",
      },
    ],
  },

  // ------------------------------------------------------------- ring support
  {
    id: "ring-support",
    name: "Ring Support",
    category: "RINGS",
    isAvailable: false, // rings not installed yet
    variations: [
      {
        id: "ring-support-hold",
        level: 1,
        name: "Ring Support Hold",
        shortCue: "Arms locked on the rings, body hanging still below — the foundation of all ring work.",
        instructions: [
          "Set the rings around hip height. Grip them and jump/press up until your arms are locked and your body hangs straight below the rings.",
          "Press the rings down hard, push the shoulders away from the ears and keep the rings close to your hips.",
          "Keep the body still: legs together, toes pointed, abs braced.",
          "A good hold keeps the elbows locked and the rings quiet (no wild shaking) for the full time.",
        ],
        tips: [
          "Expect shaking at first — it fades with exposure, not with effort.",
          "Keep knuckles pointing mostly forward/out; don't let the rings flare wide.",
        ],
        stopWhen: "Stop the set when the elbows unlock or the shoulders shrug to the ears.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 4, holdSec: 15 },
        equipment: RINGS_ONLY,
        scaleNotes: "Move up when calm 30 s holds are routine.",
      },
      {
        id: "ring-support-turned-out",
        level: 2,
        name: "Turned-Out Support (RTO)",
        shortCue: "Support hold with the rings rotated so the palms face forward/out.",
        instructions: [
          "Establish a solid ring support hold with locked elbows.",
          "Rotate the rings outward until the palms face forward or slightly out (thumbs pointing away from each other) — around 45° turnout to start.",
          "Keep the elbow pits facing forward and the arms locked; the turnout comes from the whole arm, not the wrist.",
          "A good hold maintains the turnout for the full time; if the rings rotate back to neutral, the hold is over.",
        ],
        tips: [
          "45° turnout held honestly beats 90° that collapses in 3 seconds.",
          "Squeeze the rings hard — grip drives the rotation strength.",
        ],
        stopWhen: "Stop the set when the turnout visibly unwinds or the elbows bend.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 4, holdSec: 10 },
        equipment: RINGS_ONLY,
        scaleNotes: "Move up when 15 s at a stable 45°+ turnout is consistent.",
      },
      {
        id: "ring-support-shrugs",
        level: 3,
        name: "Support Shrugs & Shifts",
        shortCue: "In support, shrug the shoulders up and down and shift weight ring to ring — control, not just survival.",
        instructions: [
          "Establish a locked-arm ring support hold.",
          "Slowly let the shoulders rise toward the ears, then press them back down as far as possible — one shrug rep, elbows locked throughout.",
          "After the shrugs, shift your weight toward one ring and back to the other, keeping both arms locked.",
          "A good rep is slow and even; count a set as the prescribed shrugs plus a few controlled shifts each way.",
        ],
        tips: [
          "Full range on the shrugs: real ears-to-depressed travel, not a twitch.",
          "The shifts are small — a few centimetres of lean is plenty on rings.",
        ],
        stopWhen: "Stop the set when the elbows start bending to absorb the movement.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 8 },
        equipment: RINGS_ONLY,
        scaleNotes: "Move up when shrugs and shifts stay smooth with zero elbow bend.",
      },
      {
        id: "ring-support-turned-out-long",
        level: 4,
        name: "Long Turned-Out Holds",
        shortCue: "RTO support held for extended time — the quiet, boring strength that unlocks ring dips and levers.",
        instructions: [
          "Establish a turned-out support: elbows locked, palms forward/out at 45°+ turnout.",
          "Hold for extended durations, breathing steadily, body in one still line.",
          "Keep checking: shoulders down, rings close to the hips, turnout maintained.",
          "A good hold keeps full turnout and locked elbows for 20 s or more without the rings wobbling inward.",
        ],
        tips: [
          "Accumulate total time across sets (e.g. 4×20 s) rather than chasing one max hold.",
          "If the biceps or inner elbows ache afterward, reduce turnout for a week — tendons set the pace.",
        ],
        stopWhen: "Stop the set when the turnout unwinds or shaking becomes violent.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 4, holdSec: 20 },
        equipment: RINGS_ONLY,
        scaleNotes: "Top of the family — 30 s+ calm RTO holds open the door to ring dips.",
      },
    ],
  },

  // ----------------------------------------------------------------- ring dip
  {
    id: "ring-dip",
    name: "Ring Dip",
    category: "RINGS",
    isAvailable: false, // rings not installed yet
    variations: [
      {
        id: "ring-dip-negative",
        level: 1,
        name: "Ring Dip Negative",
        shortCue: "From support, lower slowly to the bottom of a dip; get back to the top any way you like.",
        instructions: [
          "Establish a solid ring support hold, arms locked, rings close to the body.",
          "Bend the elbows and lower yourself over a 3–5 second count until the shoulders reach ring level (upper arm below parallel).",
          "Keep the rings pulled in tight to the ribs — letting them drift out is how dips are lost.",
          "At the bottom, step down or jump back to support. The rep is the lowering; a good rep is smooth, 3 s+, with no sudden drop.",
        ],
        tips: [
          "Lean the torso slightly forward as you descend — a bolt-upright dip strains the shoulders.",
          "Set the ring straps so your feet can reach the floor at the bottom.",
        ],
        stopWhen: "Stop the set when you can no longer control the last third of the descent.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 4 },
        equipment: RINGS_ONLY,
        scaleNotes: "Move up when every negative takes 5 s with the rings staying close.",
      },
      {
        id: "ring-dip-partial",
        level: 2,
        name: "Partial Ring Dip",
        shortCue: "Dips through the top half of the range — press from a shallow bend back to lockout.",
        instructions: [
          "Start in a ring support hold with locked arms.",
          "Lower to a shallow elbow bend (roughly 45–90°), keeping the rings tight to the body.",
          "Press back up to a full lockout with the shoulders pushed down at the top.",
          "A good rep locks out completely and keeps the rings from wobbling outward; deepen the bend gradually as sets get easier.",
        ],
        tips: [
          "Full lockout every rep — half-locked tops don't build support strength.",
          "Depth is the progression dial inside this level; add a little each week.",
        ],
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 5 },
        equipment: RINGS_ONLY,
        scaleNotes: "Move up when reps reach near-full depth while staying stable.",
      },
      {
        id: "ring-dip-full",
        level: 3,
        name: "Full Ring Dip",
        shortCue: "Shoulders to ring level at the bottom, locked arms at the top.",
        instructions: [
          "Start in a ring support hold, arms locked.",
          "Lower under control until the shoulders reach the rings (upper arms below parallel), torso leaning slightly forward.",
          "Press back to a full lockout, finishing with the shoulders pressed down and rings close to the hips.",
          "A good rep hits full depth and full lockout with no kipping legs and no rings flaring wide.",
        ],
        tips: [
          "Hollow body throughout: ribs down, glutes on.",
          "If a rep stalls, keep the rings close and grind — losing them outward is the only real failure mode.",
        ],
        stopWhen: "Stop the set one rep before failure; failed ring dips end in awkward shoulder positions.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 5 },
        equipment: RINGS_ONLY,
        scaleNotes: "Move up when 8 clean full dips are comfortable.",
      },
      {
        id: "ring-dip-rto",
        level: 4,
        name: "Ring Dip with Turned-Out Lockout",
        shortCue: "Full dips finishing every rep in a turned-out (RTO) lockout.",
        instructions: [
          "Perform a full ring dip: controlled descent to shoulders-at-rings depth.",
          "Press to lockout, then rotate the rings out so the palms face forward at the top — a genuine RTO finish.",
          "Hold the turned-out lockout for a full second, then rotate back to neutral and begin the next rep.",
          "A good rep includes a stable one-second RTO pause at the top; a rushed quarter-turn doesn't count.",
        ],
        tips: [
          "The RTO second at the top is the exercise — don't cheat it short.",
          "Reduce reps compared to normal dips; the turnout taxes the biceps tendons.",
        ],
        stopWhen: "Stop the set when the turnout at lockout starts collapsing early.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 4 },
        equipment: RINGS_ONLY,
        scaleNotes: "Top of the family — add reps slowly, then consider weighted dips.",
      },
    ],
  },

  // ------------------------------------------------------------- skin the cat
  {
    id: "skin-the-cat",
    name: "Skin the Cat",
    category: "PULL",
    isAvailable: false, // rings not installed yet
    variations: [
      {
        id: "skin-the-cat-inverted-tuck",
        level: 1,
        name: "Inverted Tuck Hang",
        shortCue: "Hang from the rings, tuck up and roll back until your hips pass through your arms — and hold.",
        instructions: [
          "Hang from the rings with straight arms, feet on or near the floor to spot yourself.",
          "Tuck the knees to the chest and roll backward, lifting the hips up and through the arms until you are upside down in a tucked ball.",
          "Hold this inverted tuck, gripping hard, arms straight.",
          "Roll back forward to the start under control. A good rep reaches a still inverted tuck and returns without dropping.",
        ],
        tips: [
          "Keep the arms straight — bending them mid-roll costs control.",
          "Set the rings low enough to bail to your feet at any point.",
        ],
        stopWhen: "Stop the set when grip fatigue makes the roll-back feel insecure.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 4 },
        equipment: RINGS_ONLY,
        scaleNotes: "Move up when rolling into and out of the inverted tuck feels casual.",
      },
      {
        id: "skin-the-cat-tucked",
        level: 2,
        name: "Tucked Skin the Cat",
        shortCue: "Roll all the way through: past inverted, feet dropping behind you toward the floor, then reverse.",
        instructions: [
          "From a straight-arm hang, tuck and roll backward through the inverted position.",
          "Keep rotating slowly, letting the feet travel down behind you until the shoulders reach a comfortable stretch (a shallow German hang), knees still tucked.",
          "Pause for a breath at the end range.",
          "Reverse the movement — pull the knees hard to the chest and roll back through inverted to the start. A good rep goes through and back with straight arms and no jerky drops.",
        ],
        tips: [
          "Go a little further into the shoulder stretch each week — never force end range.",
          "Slow rotation is the safety mechanism; momentum is the enemy here.",
        ],
        stopWhen: "Stop the set at any sharp shoulder sensation or when the rotation stops being slow.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 3 },
        equipment: RINGS_ONLY,
        scaleNotes: "Move up when full tucked rotations with a comfortable pause are easy both directions.",
      },
      {
        id: "skin-the-cat-pike",
        level: 3,
        name: "Piked Skin the Cat",
        shortCue: "The same rotation with straighter legs — more lever, more control demanded.",
        instructions: [
          "From a straight-arm hang, lift the legs in a pike (knees as straight as possible) and roll backward through inverted.",
          "Continue the rotation with legs piked until you reach the end-range stretch position.",
          "Pause, then reverse back through inverted to the start, keeping the legs piked and arms straight throughout.",
          "A good rep keeps visibly straighter knees than the tucked version for the entire circle.",
        ],
        tips: [
          "Straighter legs make you 'heavier' — expect the rotation to demand real abdominal compression.",
          "If the knees bend at the hard points, note where and fight them straight next rep.",
        ],
        stopWhen: "Stop the set when the legs collapse to a full tuck mid-rotation.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 3 },
        equipment: RINGS_ONLY,
        scaleNotes: "Move up when piked circles are smooth with a controlled pause at end range.",
      },
      {
        id: "skin-the-cat-german-hang",
        level: 4,
        name: "Skin the Cat to German Hang",
        shortCue: "Full rotation into a deep, deliberate German hang hold — then pull back out.",
        instructions: [
          "Perform a skin the cat rotation (tucked or piked) through inverted.",
          "At the end of the rotation, extend the body and let the shoulders sink into a deep German hang: arms straight overhead-behind you, body hanging below, chest toward the floor.",
          "Hold the German hang for the prescribed breaths/seconds, breathing calmly.",
          "Pull the knees in and rotate back out to the start. A good rep includes a still 5–10 s German hang and a controlled exit — dropping out to the floor doesn't count.",
        ],
        tips: [
          "The German hang is a loaded shoulder stretch — depth comes over months.",
          "Grip stays firm; loose hands in a German hang is how people fall.",
        ],
        stopWhen: "Stop the set at any sharp anterior-shoulder pain — end range should stretch, never stab.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 3 },
        equipment: RINGS_ONLY,
        scaleNotes: "Top of the family — deepen the hang and straighten the body over time.",
      },
    ],
  },

  // -------------------------------------------------------------- front lever
  {
    id: "front-lever",
    name: "Front Lever",
    category: "PULL",
    isAvailable: false, // pull-up bar not installed yet
    variations: [
      {
        id: "front-lever-tuck",
        level: 1,
        name: "Tuck Front Lever",
        shortCue: "Hang from the bar, pull the hips up and back until the torso is horizontal, knees tucked.",
        instructions: [
          "Hang from a pull-up bar with straight arms, hands shoulder-width, overhand grip.",
          "Pull the shoulder blades down and back, then lift the knees to the chest while tipping the torso backward.",
          "Keep pulling until your back is parallel to the floor, face up, knees tucked tight, arms straight.",
          "A good hold keeps the back horizontal (hips level with the shoulders) with locked arms; hips sagging below the shoulders ends the rep.",
        ],
        tips: [
          "Push the bar toward your hips with straight arms — that lat pressure is what holds you up.",
          "Film from the side; almost everyone thinks they're horizontal when they're 30° off.",
        ],
        stopWhen: "Stop the set when the hips drop or the elbows bend.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 4, holdSec: 10 },
        equipment: BAR_ONLY,
        scaleNotes: "Move up when 15 s truly-horizontal tuck holds are consistent.",
      },
      {
        id: "front-lever-advanced-tuck",
        level: 2,
        name: "Advanced Tuck Front Lever",
        shortCue: "Tuck lever with the hips opened to ~90° — thighs vertical-ish, back flat and horizontal.",
        instructions: [
          "Set up a tuck front lever: horizontal back, straight arms.",
          "Open the hip angle so the knees move away from the chest until thighs point roughly at the ceiling, shins still folded.",
          "Flatten the lower back — the rounder your back, the easier and less honest the hold.",
          "A good hold keeps the back flat and horizontal with the opened hip angle for the full time.",
        ],
        tips: [
          "Open the hips a few degrees at a time across sessions.",
          "Squeeze the glutes to control the hip angle.",
        ],
        stopWhen: "Stop the set when the knees creep back to the chest or the hips sink.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 4, holdSec: 8 },
        equipment: BAR_ONLY,
        scaleNotes: "Move up when 10–12 s flat-back advanced tucks are solid.",
      },
      {
        id: "front-lever-one-leg",
        level: 3,
        name: "One-Leg Front Lever",
        shortCue: "One leg extended fully in line with the body, the other tucked.",
        instructions: [
          "Establish an advanced tuck front lever, back horizontal.",
          "Extend one leg fully until it is straight and in line with your flat, horizontal torso; keep the other knee tucked.",
          "Keep the arms locked, shoulder blades pulling down, hips level — the extended leg must not droop below body line.",
          "A good hold keeps the extended leg locked and horizontal for the full time. Train both sides evenly.",
        ],
        tips: [
          "Point the toe of the extended leg and reach it long — a soft leg is a heavy leg.",
          "If the body sags, retuck for a second, re-set the line, extend again.",
        ],
        stopWhen: "Stop the set when the extended leg or hips drop below horizontal.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 3, holdSec: 6, perSide: true },
        equipment: BAR_ONLY,
        scaleNotes: "Move up when 8–10 s per side with a flat body line is repeatable.",
      },
      {
        id: "front-lever-straddle",
        level: 4,
        name: "Straddle Front Lever",
        shortCue: "Both legs extended but split wide — shorter lever than the full lay.",
        instructions: [
          "From an advanced tuck or one-leg lever, extend both legs while splitting them as wide as your hips allow.",
          "Lock the knees and keep the entire body — shoulders, hips, legs — in one horizontal plane.",
          "Keep pressing the bar toward the hips with straight arms.",
          "A good hold is a flat, horizontal straddle with locked knees; bent knees or piked hips end the rep.",
        ],
        tips: [
          "A wider straddle is genuinely easier — work hip mobility alongside this.",
          "Squeeze the glutes hard to stop the legs from sinking.",
        ],
        stopWhen: "Stop the set when the line breaks at the hips.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 3, holdSec: 5 },
        equipment: BAR_ONLY,
        scaleNotes: "Move up when 8 s flat straddle holds are consistent while narrowing the straddle.",
      },
      {
        id: "front-lever-full",
        level: 5,
        name: "Full Front Lever",
        shortCue: "The full lay: body in one straight horizontal line under the bar, arms locked.",
        instructions: [
          "From a straddle lever or directly from a hang, bring the legs together and extend the body into one straight line, face up, parallel to the floor.",
          "Arms stay locked; shoulder blades pull down and back; the whole body from ears to toes is one rigid plank.",
          "Hold, breathing in small sips.",
          "A good hold is any genuinely horizontal, straight-body hold of 3 s+ — build duration from there.",
        ],
        tips: [
          "Total-body tension: glutes, quads, abs, lats all firing at once.",
          "Short, frequent, fresh attempts build this hold; grinding long sets does not.",
        ],
        stopWhen: "Stop the set the instant the hips break the line — partial-height 'levers' train the wrong thing.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 3, holdSec: 5 },
        equipment: BAR_ONLY,
        scaleNotes: "Top of the family — extend toward 10 s, then explore lever pulls.",
      },
    ],
  },

  // --------------------------------------------------------------- back lever
  {
    id: "back-lever",
    name: "Back Lever",
    category: "PULL",
    isAvailable: false, // rings not installed yet
    variations: [
      {
        id: "back-lever-tuck",
        level: 1,
        name: "Tuck Back Lever",
        shortCue: "Roll through to face-down under the rings, knees tucked, back horizontal.",
        instructions: [
          "Hang from the rings and roll backward through inverted (as in skin the cat) until your body faces the floor, arms straight behind you.",
          "Tuck the knees tight to the chest and lift the hips until the back is roughly parallel to the floor.",
          "Keep the arms locked and the shoulders actively pressing down into the rings.",
          "A good hold keeps the body horizontal and still, face down, for the full time; exit by rolling back the way you came.",
        ],
        tips: [
          "Comfortable skin-the-cat rotations are the prerequisite — the entry IS a skin the cat.",
          "Squeeze the rings hard; grip slippage here is a real fall risk.",
        ],
        stopWhen: "Stop the set at any sharp biceps or anterior-shoulder sensation — the back lever loads both heavily.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 4, holdSec: 10 },
        equipment: RINGS_ONLY,
        scaleNotes: "Move up when 15 s stable tuck back levers are easy.",
      },
      {
        id: "back-lever-advanced-tuck",
        level: 2,
        name: "Advanced Tuck Back Lever",
        shortCue: "Tuck back lever with the hips opened to ~90°, back flat.",
        instructions: [
          "Establish a tuck back lever, face down, back horizontal.",
          "Open the hip angle so the knees move away from the chest, thighs pointing toward the floor, shins folded.",
          "Flatten the back and keep the hips level with the shoulders.",
          "A good hold keeps the opened angle and flat back for the full time without the chest dropping.",
        ],
        tips: [
          "Open the hips gradually — every degree adds load to the biceps tendons.",
          "Glutes on hard; they own the hip angle.",
        ],
        stopWhen: "Stop the set when the chest drops below the hips or the elbows start to bend.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 3, holdSec: 8 },
        equipment: RINGS_ONLY,
        scaleNotes: "Move up when 10–12 s flat-back holds at the open angle are solid.",
      },
      {
        id: "back-lever-straddle",
        level: 3,
        name: "Straddle Back Lever",
        shortCue: "Legs extended and split wide, whole body horizontal and face down.",
        instructions: [
          "From an advanced tuck back lever, extend both legs while splitting them wide.",
          "Lock the knees and bring the whole body into one horizontal, face-down plane.",
          "Keep the arms straight and shoulders pressing down; do not let the chest sink.",
          "A good hold is flat and horizontal with locked knees; a sagging chest or bent knees ends the rep.",
        ],
        tips: [
          "Widen the straddle as far as mobility allows — it meaningfully shortens the lever.",
          "Ease into each hold over a second; snapping into position spikes tendon load.",
        ],
        stopWhen: "Stop the set at any inner-elbow (biceps tendon) ache — back off for days, not reps.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 3, holdSec: 6 },
        equipment: RINGS_ONLY,
        scaleNotes: "Move up when 8 s flat straddle holds are routine while narrowing the straddle.",
      },
      {
        id: "back-lever-full",
        level: 4,
        name: "Full Back Lever",
        shortCue: "Body in one straight line, face down, horizontal under the rings.",
        instructions: [
          "From a straddle back lever, squeeze the legs together into one straight, horizontal line, face down.",
          "Arms locked, shoulders pressed down, glutes and abs braced to keep the hips from sagging or piking.",
          "Hold still, breathing in small sips.",
          "A good hold is a genuinely straight, horizontal body for 3 s+ — build duration gradually; exit by tucking and rolling out.",
        ],
        tips: [
          "Keep sets short and fresh; the biceps tendons accumulate fatigue silently.",
          "Film from the side — hip height is impossible to judge from inside the hold.",
        ],
        stopWhen: "Stop the set the moment the hips break the line or the elbows bend.",
        prescriptionType: "HOLD_SEC",
        defaultPrescription: { sets: 3, holdSec: 5 },
        equipment: RINGS_ONLY,
        scaleNotes: "Top of the family — extend toward 10 s clean before any straight-arm pull-outs.",
      },
    ],
  },

  // ----------------------------------------------------------- archer push-up
  {
    id: "archer-push-up",
    name: "Archer Push-Up",
    category: "PUSH",
    isAvailable: true,
    variations: [
      {
        id: "archer-push-up-side-shift",
        level: 1,
        name: "Wide Push-Up with Side Shift",
        shortCue: "Very wide push-up, lowering toward one hand at a time.",
        instructions: [
          "Set up a push-up position with hands roughly 1.5× shoulder-width, fingers pointing slightly out.",
          "Lower your chest toward ONE hand, bending that elbow while the other arm stays straighter.",
          "Press back up to the middle, then lower toward the other hand.",
          "One rep = one lower-and-press to a side; keep the hips level and square to the floor throughout. A good rep brings the chest clearly over the working hand.",
        ],
        tips: [
          "Hips stay quiet — if they swing side to side, slow down.",
          "The further you shift, the closer this gets to the real archer; increase the shift over weeks.",
        ],
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 6, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when the non-working arm stays nearly straight on every rep.",
      },
      {
        id: "archer-push-up-full",
        level: 2,
        name: "Archer Push-Up",
        shortCue: "Wide push-up lowering fully to one hand while the other arm stays completely straight.",
        instructions: [
          "Set up wider than 1.5× shoulder-width, the straight-arm-side hand turned out to let the wrist rotate as you move.",
          "Lower your chest all the way to one hand; the opposite arm stays completely straight, sliding into a T like an archer drawing a bow.",
          "Press back up using mostly the bent arm, keeping the straight arm locked.",
          "A good rep: chest touches (or nearly touches) at the working hand, straight arm never bends, hips stay level.",
        ],
        tips: [
          "Think 'one-arm push-up with a kickstand' — load the working side deliberately.",
          "Turn the straight-arm hand out (fingers away) to keep the wrist comfortable.",
        ],
        stopWhen: "Stop the set when the 'straight' arm starts bending to help.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 5, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Move up when 6–8 strict reps per side are smooth with a genuinely straight assist arm.",
      },
      {
        id: "archer-push-up-elevated",
        level: 3,
        name: "Feet-Elevated Archer Push-Up",
        shortCue: "Archer push-ups with the feet on a box — more load on the working arm.",
        instructions: [
          "Place your feet on a sturdy box or bench (30–50 cm) and set the hands wide as for a normal archer push-up.",
          "Lower the chest fully to one hand, keeping the opposite arm locked straight.",
          "Press back up with the working arm, hips level, body in one line from head to elevated heels.",
          "A good rep meets the strict archer standard under the increased load — full depth, straight assist arm, no hip twist.",
        ],
        tips: [
          "Raise the feet gradually; each 10 cm noticeably loads the working arm.",
          "This is direct one-arm push-up preparation — treat reps as strength work, low and clean.",
        ],
        stopWhen: "Stop the set when depth shortens or the hips start rotating to cheat.",
        prescriptionType: "REPS",
        defaultPrescription: { sets: 3, reps: 4, perSide: true },
        equipment: BODYWEIGHT_ONLY,
        scaleNotes: "Top of the family — from here, explore one-arm push-up progressions.",
      },
    ],
  },
];

export const SKILL_FAMILIES_BY_ID: Record<string, SkillFamily> = Object.fromEntries(
  SKILL_FAMILIES.map((family) => [family.id, family]),
);

export function getSkillVariation(familyId: string, variationId: string): SkillVariation | null {
  const family = SKILL_FAMILIES_BY_ID[familyId];
  if (!family) return null;
  return family.variations.find((v) => v.id === variationId) ?? null;
}

/**
 * The variation exactly one level up or down within the same family.
 * Returns null at the boundary (no easier/harder variation) or on unknown ids.
 */
export function neighborVariation(
  familyId: string,
  variationId: string,
  direction: "up" | "down",
): SkillVariation | null {
  const family = SKILL_FAMILIES_BY_ID[familyId];
  if (!family) return null;
  const current = family.variations.find((v) => v.id === variationId);
  if (!current) return null;
  const targetLevel = direction === "up" ? current.level + 1 : current.level - 1;
  return family.variations.find((v) => v.level === targetLevel) ?? null;
}

/**
 * Default starting variation per family for THIS athlete (spec: he already
 * walks on his hands, cannot yet hold a full L-sit, and pistols to a box).
 * Families without an entry default to level 1 elsewhere in the app.
 * Only AVAILABLE families are listed — equipment-gated families start at
 * level 1 once their equipment arrives.
 */
export const SKILL_STARTING_LEVELS: Record<string, string> = {
  "handstand-control": "handstand-walk", // already walks 10 m+ on his hands
  "l-sit": "l-sit-tuck", // cannot yet hold a full L-sit
  "pistol-squat": "pistol-box",
  "handstand-push-up": "hspu-pike-elevated", // strong hand-balancer; elevated pike is a safe start
  "crow-to-tuck-planche": "crow-hold", // crow is trivial for a handstand walker
  "planche-lean": "planche-lean-hold",
  "shrimp-squat": "shrimp-assisted",
  "dragon-squat": "dragon-assisted",
  "archer-push-up": "archer-push-up-side-shift",
};
