import type { DayTemplate } from "../types";

// Week 2 program (starts 2026-09-05). Coached progression from Week 1.
// Templates describe the future; sessions snapshot them at start (spec §23) —
// so publishing this week never touches Week 1's completed history.
//
// Week 1 (days 1–4) actuals used to load this week:
//   halo 12 kg = "too easy"        → 16 kg
//   C&P 16 kg  = solid (elbow niggle on cleans) → keep 16 kg
//   one-arm row 20 kg × 10         → 20 kg workhorse; 24 kg for heavy singles
//   slow goblet 24 kg / carry 24 kg = easy → 24 kg for grinds & carries
//   horn curl 12 kg 8/8/6          → 12 kg is right
//   handstand → handstand-walk-short, l-sit → support hold (both auto-baselined)
//
// The warm-up + a short skill block are injected at start by generate/plan.ts;
// days without their own skill slot receive one rotating calisthenics block.

export const WEEK2: DayTemplate[] = [
  // ============================================================ DAY 1
  {
    day: 1,
    name: "FULL-BODY STRENGTH",
    intensity: "MEDIUM",
    emphasis: "QUALITY",
    goal: "Whole-body strength, shoulders and a handstand skill block. Strong, clean reps — not cardio.",
    quote: "Strong reps. No garbage reps.",
    sections: [
      {
        id: "w2d1-s1",
        type: "SKILL",
        title: "HANDSTAND",
        emphasis: "SKILL",
        intro: "8–10 min of quality attempts at your current progression. Stop before form fades.",
        exerciseId: "handstand",
        durationMin: 9,
        trackBestHold: true,
        trackAttempts: true,
      },
      {
        id: "w2d1-s2",
        type: "CIRCUIT",
        title: "STRENGTH — 4 ROUNDS",
        intro: "4 quality rounds. Rest ~75–90 sec between rounds. Weights may differ per exercise.",
        rounds: 4,
        prescriptions: [
          {
            id: "w2d1-goblet",
            kind: "SETS",
            exerciseId: "goblet-squat",
            grip: "HORNS",
            sets: 1,
            reps: 8,
            weightKg: 24,
          },
          {
            id: "w2d1-row",
            kind: "SETS",
            exerciseId: "ballistic-row",
            grip: "HANDLE",
            sets: 1,
            reps: 8,
            perSide: true,
            weightKg: 20,
          },
          {
            id: "w2d1-dip",
            kind: "SETS",
            exerciseId: "push-up",
            grip: "BODYWEIGHT",
            gripNotes: "Dip substitute (no dip station/rings) — elevate the feet to make 6–10 genuinely hard.",
            sets: 1,
            reps: "6–10",
          },
          {
            id: "w2d1-rdl",
            kind: "SETS",
            exerciseId: "single-leg-rdl",
            grip: "HANDLE",
            sets: 1,
            reps: "8–10",
            perSide: true,
            weightKg: 20,
          },
        ],
      },
      {
        id: "w2d1-s3",
        type: "CIRCUIT",
        title: "ABS — 3 ROUNDS",
        intro: "Direct core. Quality holds, no breath-holding grind.",
        rounds: 3,
        prescriptions: [
          {
            id: "w2d1-deadbug",
            kind: "SETS",
            exerciseId: "dead-bug",
            grip: "BODYWEIGHT",
            sets: 1,
            reps: "8–10",
            perSide: true,
          },
          {
            id: "w2d1-hollow",
            kind: "SETS",
            exerciseId: "hollow-hold",
            grip: "BODYWEIGHT",
            sets: 1,
            durationSec: 25,
          },
          {
            id: "w2d1-sideplank",
            kind: "SETS",
            exerciseId: "side-plank",
            grip: "BODYWEIGHT",
            sets: 1,
            durationSec: 30,
            perSide: true,
          },
        ],
      },
    ],
  },

  // ============================================================ DAY 2
  {
    day: 2,
    name: "BALLISTIC CONDITIONING",
    intensity: "MEDIUM",
    emphasis: "OUTPUT",
    goal: "Athletic, sweaty, controlled power work. Crisp swings and snatches — around RPE 7–8, not max effort.",
    quote: "Fast hips, quiet technique.",
    sections: [
      {
        id: "w2d2-s1",
        type: "STRAIGHT_SETS",
        title: "SNATCH TECHNIQUE PREP",
        intro: "Short primer. Light and crisp — grooving the punch-through, not conditioning yet.",
        prescriptions: [
          {
            id: "w2d2-snatch-prep",
            restSeconds: 60,
            kind: "SETS",
            exerciseId: "kb-snatch",
            grip: "HANDLE",
            sets: 2,
            reps: 3,
            perSide: true,
            weightKg: 12,
          },
        ],
      },
      {
        id: "w2d2-s2",
        type: "EMOM",
        title: "SWING / SNATCH EMOM",
        intro: "12 min. Odd minutes swings, even minutes snatches. ONE bell that keeps BOTH crisp. Rest the rest of each minute.",
        minutes: 12,
        blockWeightKg: 16,
        pattern: [
          {
            id: "w2d2-swing",
            kind: "TIMED_MOVEMENT",
            exerciseId: "kb-swing",
            grip: "HANDLE",
            reps: 12,
            watchFor: ["Hip-driven", "Neutral spine", "Relax the shoulders", "Stop if form slips"],
          },
          {
            id: "w2d2-snatch",
            kind: "TIMED_MOVEMENT",
            exerciseId: "kb-snatch",
            grip: "HANDLE",
            reps: 5,
            perSide: true,
            watchFor: ["Punch through — no wrist bang", "Hip drive", "Neutral spine", "Loose grip"],
          },
        ],
      },
      {
        id: "w2d2-s3",
        type: "CIRCUIT",
        title: "ACCESSORY — 3 ROUNDS",
        intro: "Controlled rotational and grip work between the hard breathing.",
        rounds: 3,
        prescriptions: [
          {
            id: "w2d2-gravedigger",
            kind: "SETS",
            exerciseId: "kb-gravedigger",
            grip: "HANDLE",
            sets: 1,
            reps: 8,
            perSide: true,
            weightKg: 12,
          },
          {
            id: "w2d2-halo",
            kind: "SETS",
            exerciseId: "halo",
            grip: "HORNS",
            sets: 1,
            reps: 6,
            eachDirection: true,
            weightKg: 16,
          },
          {
            id: "w2d2-dsc",
            kind: "SETS",
            exerciseId: "deep-squat-curl",
            grip: "HORNS",
            sets: 1,
            reps: 8,
            weightKg: 12,
          },
        ],
      },
      {
        id: "w2d2-s4",
        type: "CIRCUIT",
        title: "ABS — 3 ROUNDS",
        intro: "Keep the toe comfortable in the plank drag; scale the setup if needed.",
        rounds: 3,
        prescriptions: [
          {
            id: "w2d2-drag",
            kind: "SETS",
            exerciseId: "north-south-plank-drag",
            grip: "HANDLE",
            sets: 1,
            reps: 7,
            perSide: true,
            weightKg: 12,
          },
          {
            id: "w2d2-revcrunch",
            kind: "SETS",
            exerciseId: "reverse-crunch",
            grip: "BODYWEIGHT",
            sets: 1,
            reps: "10–15",
          },
          {
            id: "w2d2-hollow",
            kind: "SETS",
            exerciseId: "hollow-hold",
            grip: "BODYWEIGHT",
            sets: 1,
            durationSec: 25,
          },
        ],
      },
    ],
  },

  // ============================================================ DAY 3
  {
    day: 3,
    name: "UPPER BODY + UNILATERAL",
    intensity: "MEDIUM",
    emphasis: "QUALITY",
    goal: "Meaningful pressing, pulling and single-leg strength plus real trunk work. Stimulate, don't bury.",
    quote: "Own every single-side rep.",
    sections: [
      {
        id: "w2d3-s1",
        type: "SKILL_PRACTICE",
        title: "L-SIT",
        emphasis: "SKILL",
        intro: "5–8 min at your current L-sit progression. Quality attempts, full rest.",
        familyId: "l-sit",
        variationId: "l-sit-support-hold",
        prescription: { sets: 4, holdSec: 20, restSec: 45 },
        targetMinutes: 6,
      },
      {
        id: "w2d3-s2",
        type: "CIRCUIT",
        title: "STRENGTH — 4 ROUNDS",
        intro: "4 rounds, rest as needed. Clean unilateral reps.",
        rounds: 4,
        prescriptions: [
          {
            id: "w2d3-floorpress",
            kind: "SETS",
            exerciseId: "floor-press",
            grip: "HANDLE",
            gripNotes: "Single arm",
            sets: 1,
            reps: 8,
            perSide: true,
            weightKg: 20,
          },
          {
            id: "w2d3-row",
            kind: "SETS",
            exerciseId: "one-arm-row",
            grip: "HANDLE",
            gripNotes: "Supported KB row (gorilla row needs two bells).",
            sets: 1,
            reps: 8,
            perSide: true,
            weightKg: 24,
          },
          {
            id: "w2d3-lunge",
            kind: "SETS",
            exerciseId: "front-rack-reverse-lunge",
            grip: "HANDLE",
            gripNotes: "Rack position. Toe-friendly reverse lunge.",
            sets: 1,
            reps: 8,
            perSide: true,
            weightKg: 20,
          },
          {
            id: "w2d3-ballrow",
            kind: "SETS",
            exerciseId: "ballistic-row",
            grip: "HANDLE",
            gripNotes: "Ring-row substitute (no rings) — explosive up, controlled down.",
            sets: 1,
            reps: "8–12",
            perSide: true,
            weightKg: 20,
          },
        ],
      },
      {
        id: "w2d3-s3",
        type: "CIRCUIT",
        title: "CORE — 3 ROUNDS",
        intro: "Real trunk fatigue, controlled — no spinal flailing.",
        rounds: 3,
        prescriptions: [
          {
            id: "w2d3-tuck",
            kind: "SETS",
            exerciseId: "seated-knee-tuck",
            grip: "BODYWEIGHT",
            sets: 1,
            reps: "10–15",
          },
          {
            id: "w2d3-twist",
            kind: "SETS",
            exerciseId: "kb-russian-twist",
            grip: "HORNS",
            sets: 1,
            reps: 10,
            perSide: true,
            weightKg: 12,
          },
          {
            id: "w2d3-carry",
            kind: "SETS",
            exerciseId: "suitcase-carry",
            grip: "HANDLE",
            gripNotes: "Suitcase hold or carry.",
            sets: 1,
            durationSec: 40,
            perSide: true,
            weightKg: 24,
          },
        ],
      },
    ],
  },

  // ============================================================ DAY 4
  {
    day: 4,
    name: "HARD DAY",
    intensity: "HARD",
    emphasis: "OUTPUT",
    goal: "The one legitimately hard session of the week (~RPE 8–8.5). Move continuously but cleanly — no ugly reps.",
    quote: "Yep. That was a workout.",
    sections: [
      {
        id: "w2d4-s1",
        type: "AMRAP",
        title: "18 MIN AMRAP",
        intro: "ONE bell the whole way. No target round count — keep every rep clean and just keep moving.",
        minutes: 18,
        blockWeightKg: 16,
        round: [
          {
            id: "w2d4-swing",
            kind: "TIMED_MOVEMENT",
            exerciseId: "kb-swing",
            grip: "HANDLE",
            reps: 10,
          },
          {
            id: "w2d4-pushpress",
            kind: "TIMED_MOVEMENT",
            exerciseId: "clean-push-press",
            grip: "HANDLE",
            reps: 5,
            perSide: true,
          },
          {
            id: "w2d4-goblet",
            kind: "TIMED_MOVEMENT",
            exerciseId: "goblet-squat",
            grip: "HORNS",
            reps: 8,
          },
          {
            id: "w2d4-row",
            kind: "TIMED_MOVEMENT",
            exerciseId: "one-arm-row",
            grip: "HANDLE",
            reps: 6,
            perSide: true,
          },
        ],
      },
      {
        id: "w2d4-s2",
        type: "EMOM",
        title: "AB FINISHER",
        intro: "6 min. Odd minutes hollow, even minutes side plank (alternate sides). Hold ~30–40 sec, rest the remainder.",
        minutes: 6,
        blockWeightKg: null,
        pattern: [
          {
            id: "w2d4-hollow",
            kind: "TIMED_MOVEMENT",
            exerciseId: "hollow-hold",
            displayName: "Hollow hold — 30–40 sec",
            grip: "BODYWEIGHT",
            reps: 1,
            bodyweight: true,
            watchFor: ["Low back pressed down", "Ribs down", "Stop when shaking breaks the shape"],
          },
          {
            id: "w2d4-sideplank",
            kind: "TIMED_MOVEMENT",
            exerciseId: "side-plank",
            displayName: "Side plank — 30–40 sec (alternate sides each round)",
            grip: "BODYWEIGHT",
            reps: 1,
            bodyweight: true,
            watchFor: ["Straight line head to feet", "Hips high", "Shoulder stacked"],
          },
        ],
      },
    ],
  },

  // ============================================================ DAY 5
  {
    day: 5,
    name: "HYPERTROPHY + ACCESSORY",
    intensity: "MEDIUM",
    emphasis: "VOLUME",
    goal: "Optional muscle-building volume (~RPE 6.5–7.5). Useful work without smashing recovery.",
    quote: "Build muscle. Leave something in the tank.",
    sections: [
      {
        id: "w2d5-s1",
        type: "CIRCUIT",
        title: "HYPERTROPHY — 3 ROUNDS",
        intro: "3–4 quality rounds, moderate reps. Add a 4th round if you feel good.",
        rounds: 3,
        prescriptions: [
          {
            id: "w2d5-dsc",
            kind: "SETS",
            exerciseId: "deep-squat-curl",
            grip: "HORNS",
            sets: 1,
            reps: "8–10",
            weightKg: 12,
          },
          {
            id: "w2d5-floorpress",
            kind: "SETS",
            exerciseId: "floor-press",
            grip: "HANDLE",
            sets: 1,
            reps: 8,
            perSide: true,
            weightKg: 20,
          },
          {
            id: "w2d5-row",
            kind: "SETS",
            exerciseId: "one-arm-row",
            grip: "HANDLE",
            sets: 1,
            reps: 10,
            perSide: true,
            weightKg: 20,
          },
          {
            id: "w2d5-rdl",
            kind: "SETS",
            exerciseId: "single-leg-rdl",
            grip: "HANDLE",
            gripNotes: "Single-leg — toe-friendly.",
            sets: 1,
            reps: 8,
            perSide: true,
            weightKg: 20,
          },
          {
            id: "w2d5-atw",
            kind: "SETS",
            exerciseId: "around-the-world",
            grip: "HANDLE",
            sets: 1,
            reps: 8,
            eachDirection: true,
            weightKg: 16,
          },
          {
            id: "w2d5-carry",
            kind: "SETS",
            exerciseId: "suitcase-carry",
            grip: "HANDLE",
            gripNotes: "Carry or hold.",
            sets: 1,
            durationSec: 40,
            perSide: true,
            weightKg: 24,
          },
        ],
      },
      {
        id: "w2d5-s2",
        type: "SKILL",
        title: "HANDSTAND",
        emphasis: "SKILL",
        intro: "5–10 min easy handstand (or L-sit) practice. Play, don't grind.",
        exerciseId: "handstand",
        durationMin: 8,
        trackBestHold: true,
      },
      {
        id: "w2d5-s3",
        type: "CIRCUIT",
        title: "ABS — 3 ROUNDS",
        intro: "Direct ab movements kept fresh from earlier in the week.",
        rounds: 3,
        prescriptions: [
          {
            id: "w2d5-drag",
            kind: "SETS",
            exerciseId: "plank-kb-drag",
            grip: "HANDLE",
            sets: 1,
            reps: "8–10",
            weightKg: 12,
          },
          {
            id: "w2d5-deadbug",
            kind: "SETS",
            exerciseId: "dead-bug",
            grip: "BODYWEIGHT",
            sets: 1,
            reps: "8–10",
            perSide: true,
          },
        ],
      },
    ],
  },

  // ============================================================ DAY 6
  {
    day: 6,
    name: "MOVEMENT + RECOVERY",
    intensity: "LIGHT",
    emphasis: "SKILL",
    goal: "Optional easy technique, mobility and light core (~RPE 5–6). Finish better than you started.",
    quote: "Leave feeling better than you arrived.",
    sections: [
      {
        id: "w2d6-s1",
        type: "STRAIGHT_SETS",
        title: "TURKISH GET-UP",
        intro: "Slow, deliberate technique. Half get-ups (stop before the standing lunge) if the toe complains.",
        prescriptions: [
          {
            id: "w2d6-tgu",
            restSeconds: 60,
            kind: "SETS",
            exerciseId: "turkish-get-up",
            grip: "HANDLE",
            sets: 3,
            reps: 3,
            perSide: true,
            weightKg: 12,
          },
        ],
      },
      {
        id: "w2d6-s2",
        type: "FLOW",
        title: "MOVEMENT FLOW",
        intro: "2 easy rounds. 12 kg for the whole flow. Smooth and relaxed.",
        rounds: 2,
        blockWeightKg: 12,
        movements: [
          {
            id: "w2d6-halo",
            kind: "TIMED_MOVEMENT",
            exerciseId: "halo",
            grip: "HORNS",
            reps: 5,
            eachDirection: true,
          },
          {
            id: "w2d6-atw",
            kind: "TIMED_MOVEMENT",
            exerciseId: "around-the-world",
            grip: "HANDLE",
            reps: 8,
            eachDirection: true,
          },
          {
            id: "w2d6-windmill",
            kind: "TIMED_MOVEMENT",
            exerciseId: "low-windmill",
            grip: "HANDLE",
            reps: 5,
            perSide: true,
          },
          {
            id: "w2d6-fig8",
            kind: "TIMED_MOVEMENT",
            exerciseId: "figure-8",
            grip: "HANDLE",
            reps: 6,
            eachDirection: true,
          },
        ],
      },
      {
        id: "w2d6-s3",
        type: "STRAIGHT_SETS",
        title: "EASY CARRY",
        prescriptions: [
          {
            id: "w2d6-carry",
            restSeconds: 45,
            kind: "SETS",
            exerciseId: "suitcase-carry",
            grip: "HANDLE",
            sets: 2,
            durationSec: 40,
            perSide: true,
            weightKg: 16,
          },
        ],
      },
      {
        id: "w2d6-s4",
        type: "STRAIGHT_SETS",
        title: "LIGHT CORE",
        prescriptions: [
          {
            id: "w2d6-deadbug",
            restSeconds: 30,
            kind: "SETS",
            exerciseId: "dead-bug",
            grip: "BODYWEIGHT",
            sets: 2,
            reps: 10,
            perSide: true,
          },
        ],
      },
    ],
  },

  // ============================================================ DAY 7
  {
    day: 7,
    name: "REST / RECOVERY",
    intensity: "REST",
    emphasis: "SKILL",
    goal: "Recover. More training helps only if recovery stays good.",
    quote: "Rest is part of the program.",
    isRest: true,
    restSuggestions: [
      "Walk",
      "Eat sufficient protein",
      "Sleep",
      "Light mobility if desired",
    ],
    sections: [],
  },
];
