import type { DayTemplate } from "../types";

// Week 1 program, transcribed from the master spec (§16).
// Templates describe the future; sessions snapshot them at start (spec §23).

export const WEEK1: DayTemplate[] = [
  // ============================================================ DAY 1
  {
    day: 1,
    name: "HARD STRENGTH",
    intensity: "HARD",
    emphasis: "QUALITY",
    goal: "Full-body strength, shoulder development, pulling strength and anti-rotation.",
    quote: "Strong reps. No garbage reps.",
    sections: [
      {
        id: "d1-s1",
        type: "SKILL",
        title: "HANDSTAND",
        emphasis: "SKILL",
        exerciseId: "handstand",
        durationMin: 8,
        trackBestHold: true,
      },
      {
        id: "d1-s2",
        type: "STRAIGHT_SETS",
        title: "HALO",
        prescriptions: [
          {
            id: "d1-halo",
            kind: "SETS",
            exerciseId: "halo",
            grip: "HORNS",
            sets: 2,
            reps: 5,
            eachDirection: true,
            weightKg: 12,
          },
        ],
      },
      {
        id: "d1-s3",
        type: "STRAIGHT_SETS",
        title: "CLEAN + STRICT PRESS",
        prescriptions: [
          {
            id: "d1-clean-press",
            kind: "SETS",
            exerciseId: "clean-strict-press",
            grip: "HANDLE",
            sets: 3,
            reps: 5,
            perSide: true,
            weightKg: 16,
          },
        ],
      },
      {
        id: "d1-s4",
        type: "STRAIGHT_SETS",
        title: "FRONT-RACK REVERSE LUNGE",
        prescriptions: [
          {
            id: "d1-lunge",
            kind: "SETS",
            exerciseId: "front-rack-reverse-lunge",
            grip: "HANDLE",
            gripNotes: "Rack position",
            sets: 3,
            reps: 6,
            perSide: true,
            weightKg: 20,
          },
        ],
      },
      {
        id: "d1-s5",
        type: "STRAIGHT_SETS",
        title: "ONE-ARM ROW",
        prescriptions: [
          {
            id: "d1-row",
            kind: "SETS",
            exerciseId: "one-arm-row",
            grip: "HANDLE",
            sets: 3,
            reps: 10,
            perSide: true,
            weightKg: 20,
          },
        ],
      },
      {
        id: "d1-s6",
        type: "STRAIGHT_SETS",
        title: "SUITCASE CARRY",
        prescriptions: [
          {
            id: "d1-carry",
            kind: "SETS",
            exerciseId: "suitcase-carry",
            grip: "HANDLE",
            sets: 3,
            durationSec: 30,
            perSide: true,
            weightKg: 24,
          },
        ],
      },
    ],
  },

  // ============================================================ DAY 2
  {
    day: 2,
    name: "LIGHT CORE + ENGINE",
    intensity: "LIGHT",
    emphasis: "SKILL",
    goal: "Core control, rotation, anti-rotation, movement practice and easy conditioning.",
    quote: "Easy days make hard days possible.",
    sections: [
      {
        id: "d2-s1",
        type: "FLOW",
        title: "CORE FLOW",
        intro: "3 relaxed rounds. 12 kg for the entire flow.",
        rounds: 3,
        blockWeightKg: 12,
        movements: [
          {
            id: "d2-atw",
            kind: "TIMED_MOVEMENT",
            exerciseId: "around-the-world",
            grip: "HANDLE",
            reps: 6,
            eachDirection: true,
          },
          {
            id: "d2-fig8",
            kind: "TIMED_MOVEMENT",
            exerciseId: "figure-8",
            grip: "HANDLE",
            reps: 6,
            eachDirection: true,
          },
          {
            id: "d2-windmill",
            kind: "TIMED_MOVEMENT",
            exerciseId: "low-windmill",
            grip: "HANDLE",
            reps: 5,
            perSide: true,
          },
          {
            id: "d2-halo",
            kind: "TIMED_MOVEMENT",
            exerciseId: "halo",
            grip: "HORNS",
            reps: 5,
            eachDirection: true,
          },
        ],
      },
      {
        id: "d2-s2",
        type: "EMOM",
        title: "EASY SWING EMOM",
        intro:
          "Easy aerobic power practice. Rest the remainder of each minute. Do NOT turn this into hard conditioning.",
        minutes: 10,
        blockWeightKg: 20,
        pattern: [
          {
            id: "d2-swing",
            kind: "TIMED_MOVEMENT",
            exerciseId: "kb-swing",
            grip: "HANDLE",
            reps: 6,
            watchFor: [
              "Hip-driven",
              "Neutral spine",
              "Relax shoulders",
              "Strong handle grip",
              "Controlled breathing",
            ],
          },
        ],
      },
      {
        id: "d2-s3",
        type: "INTERVAL",
        title: "JUMP ROPE",
        exerciseId: "jump-rope",
        rounds: 6,
        workSec: 30,
        restSec: 60,
        effort: "LIGHT effort.",
      },
    ],
  },

  // ============================================================ DAY 3
  {
    day: 3,
    name: "HARD CONDITIONING",
    intensity: "HARD",
    emphasis: "OUTPUT",
    goal: "Power and measurable full-body conditioning.",
    quote: "Today we measure.",
    sections: [
      {
        id: "d3-s1",
        type: "SKILL",
        title: "HANDSTAND",
        emphasis: "SKILL",
        intro: "Keep it easy. Hard conditioning follows.",
        exerciseId: "handstand",
        durationMin: 5,
        trackBestHold: true,
      },
      {
        id: "d3-s2",
        type: "EMOM",
        title: "SWING POWER EMOM",
        minutes: 6,
        blockWeightKg: 24,
        pattern: [
          {
            id: "d3-swing",
            kind: "TIMED_MOVEMENT",
            exerciseId: "kb-swing",
            grip: "HANDLE",
            reps: 8,
            watchFor: [
              "Explosive hips",
              "Neutral spine",
              "Bell driven by hips",
              "Arms guide rather than lift",
              "Stop if technique deteriorates",
            ],
          },
        ],
      },
      {
        id: "d3-s3",
        type: "AMRAP",
        title: "WEEK 1 BASELINE AMRAP",
        minutes: 8,
        blockWeightKg: 20,
        isBenchmark: true,
        benchmarkLabel: "WEEK 1 BASELINE — compare against Week 10",
        round: [
          {
            id: "d3-swings",
            kind: "TIMED_MOVEMENT",
            exerciseId: "kb-swing",
            grip: "HANDLE",
            reps: 8,
          },
          {
            id: "d3-goblet",
            kind: "TIMED_MOVEMENT",
            exerciseId: "goblet-squat",
            grip: "HORNS",
            reps: 6,
          },
          {
            id: "d3-pushup",
            kind: "TIMED_MOVEMENT",
            exerciseId: "push-up",
            grip: "BODYWEIGHT",
            reps: 6,
            bodyweight: true,
          },
          {
            id: "d3-row",
            kind: "TIMED_MOVEMENT",
            exerciseId: "one-arm-row",
            grip: "HANDLE",
            reps: 6,
            perSide: true,
          },
        ],
      },
    ],
  },

  // ============================================================ DAY 4
  {
    day: 4,
    name: "MEDIUM MUSCLE + STABILITY",
    intensity: "MEDIUM",
    emphasis: "VOLUME",
    goal: "Hypertrophy, chest/upper-body development, biceps, legs and stabilization.",
    quote: "Build muscle. Don't chase exhaustion.",
    sections: [
      {
        id: "d4-s1",
        type: "CIRCUIT",
        title: "ROUND WORK A",
        intro: "2 rounds in Week 1. NOT timed. Weights may change between exercises.",
        rounds: 2,
        prescriptions: [
          {
            id: "d4-halo",
            kind: "SETS",
            exerciseId: "halo",
            grip: "HORNS",
            sets: 1,
            reps: 5,
            eachDirection: true,
            weightKg: 12,
          },
          {
            id: "d4-rdl",
            kind: "SETS",
            exerciseId: "single-leg-rdl",
            grip: "HANDLE",
            sets: 1,
            reps: 8,
            perSide: true,
            weightKg: 20,
          },
          {
            id: "d4-slow-goblet",
            kind: "SETS",
            exerciseId: "slow-goblet-squat",
            grip: "HORNS",
            sets: 1,
            reps: 10,
            tempo: "3 seconds down",
            weightKg: 24,
          },
          {
            id: "d4-floor-press",
            kind: "SETS",
            exerciseId: "floor-press",
            grip: "HANDLE",
            sets: 1,
            reps: 8,
            perSide: true,
            weightKg: 20,
          },
        ],
      },
      {
        id: "d4-s2",
        type: "STRAIGHT_SETS",
        title: "HORN CURL",
        intro: "Dedicated direct arm work. Default Week 1: 12 kg (range 12–16 kg). Track every set separately.",
        prescriptions: [
          {
            id: "d4-horn-curl",
            kind: "SETS",
            exerciseId: "horn-curl",
            grip: "HORNS",
            sets: 3,
            reps: "8–12",
            weightKg: 12,
          },
        ],
      },
      {
        id: "d4-s3",
        type: "CIRCUIT",
        title: "ROUND WORK B",
        intro: "2 rounds. NOT timed.",
        rounds: 2,
        prescriptions: [
          {
            id: "d4-row",
            kind: "SETS",
            exerciseId: "one-arm-row",
            grip: "HANDLE",
            sets: 1,
            reps: 10,
            perSide: true,
            weightKg: 20,
          },
          {
            id: "d4-rack-march",
            kind: "SETS",
            exerciseId: "rack-march",
            grip: "HANDLE",
            gripNotes: "Rack position",
            sets: 1,
            durationSec: 30,
            perSide: true,
            weightKg: 20,
          },
          {
            id: "d4-side-plank",
            kind: "SETS",
            exerciseId: "side-plank",
            grip: "BODYWEIGHT",
            sets: 1,
            durationSec: 30,
            perSide: true,
          },
        ],
      },
    ],
  },

  // ============================================================ DAY 5
  {
    day: 5,
    name: "LIGHT SKILL + CORE + FOREARMS",
    intensity: "LIGHT",
    emphasis: "SKILL",
    goal: "Handstand development, shoulder health, rotational core work, arms, grip and active recovery.",
    quote: "Practice, don't prove.",
    sections: [
      {
        id: "d5-s1",
        type: "SKILL",
        title: "HANDSTAND PRACTICE",
        intro: "This session should leave you feeling better rather than destroyed.",
        exerciseId: "handstand",
        durationMin: 15,
        trackBestHold: true,
        trackAttempts: true,
      },
      {
        id: "d5-s2",
        type: "STRAIGHT_SETS",
        title: "HALO",
        prescriptions: [
          {
            id: "d5-halo",
            kind: "SETS",
            exerciseId: "halo",
            grip: "HORNS",
            sets: 3,
            reps: 5,
            eachDirection: true,
            weightKg: 12,
          },
        ],
      },
      {
        id: "d5-s3",
        type: "STRAIGHT_SETS",
        title: "AROUND THE WORLD",
        prescriptions: [
          {
            id: "d5-atw",
            kind: "SETS",
            exerciseId: "around-the-world",
            grip: "HANDLE",
            sets: 3,
            reps: 8,
            eachDirection: true,
            weightKg: 12,
          },
        ],
      },
      {
        id: "d5-s4",
        type: "STRAIGHT_SETS",
        title: "DEEP SQUAT CURL",
        intro: "Stay in a comfortable deep squat while curling.",
        prescriptions: [
          {
            id: "d5-dsc",
            kind: "SETS",
            exerciseId: "deep-squat-curl",
            grip: "HORNS",
            sets: 2,
            reps: "6–8",
            weightKg: 12,
          },
        ],
      },
      {
        id: "d5-s5",
        type: "STRAIGHT_SETS",
        title: "NORTH-SOUTH PLANK DRAG",
        prescriptions: [
          {
            id: "d5-nsdrag",
            kind: "SETS",
            exerciseId: "north-south-plank-drag",
            grip: "HANDLE",
            gripNotes: "Handle when moving bell",
            sets: 3,
            reps: 6,
            weightKg: 12,
          },
        ],
      },
      {
        id: "d5-s6",
        type: "STRAIGHT_SETS",
        title: "BOTTOM-UP HOLD",
        prescriptions: [
          {
            id: "d5-buh",
            kind: "SETS",
            exerciseId: "bottom-up-hold",
            grip: "BOTTOM_UP_HANDLE",
            sets: 3,
            durationSec: 20,
            perSide: true,
            weightKg: 8,
          },
        ],
      },
      {
        id: "d5-s7",
        type: "STRAIGHT_SETS",
        title: "BALL SQUEEZE HOLD",
        intro:
          "Default 8–12 kg; Week 1: 8 kg for 20–30 s. If the bell shape cannot be safely held by the body, mark SKIPPED — EQUIPMENT SHAPE with a note.",
        prescriptions: [
          {
            id: "d5-ball",
            kind: "SETS",
            exerciseId: "ball-squeeze-hold",
            grip: "BALL",
            sets: 2,
            durationSec: 30,
            weightKg: 8,
          },
        ],
      },
      {
        id: "d5-s8",
        type: "STRAIGHT_SETS",
        title: "DEAD BUG",
        prescriptions: [
          {
            id: "d5-deadbug",
            kind: "SETS",
            exerciseId: "dead-bug",
            grip: "BODYWEIGHT",
            sets: 3,
            reps: 8,
            perSide: true,
          },
        ],
      },
      {
        id: "d5-s9",
        type: "STRAIGHT_SETS",
        title: "HOLLOW HOLD",
        prescriptions: [
          {
            id: "d5-hollow",
            kind: "SETS",
            exerciseId: "hollow-hold",
            grip: "BODYWEIGHT",
            sets: 3,
            durationSec: 20,
          },
        ],
      },
    ],
  },

  // ============================================================ DAY 6
  {
    day: 6,
    name: "MEDIUM FULL BODY",
    intensity: "MEDIUM",
    emphasis: "VOLUME",
    goal: "Full-body work capacity without becoming another maximum conditioning day.",
    quote: "Smooth is fast.",
    sections: [
      {
        id: "d6-s1",
        type: "EMOM",
        title: "MAIN EMOM",
        intro: "The entire EMOM uses the SAME 16 kg kettlebell. Five cycles of three minutes.",
        minutes: 15,
        blockWeightKg: 16,
        pattern: [
          {
            id: "d6-cp",
            kind: "TIMED_MOVEMENT",
            exerciseId: "clean-strict-press",
            displayName: "Clean + Press — 3/side",
            grip: "HANDLE",
            reps: 6,
          },
          {
            id: "d6-goblet",
            kind: "TIMED_MOVEMENT",
            exerciseId: "goblet-squat",
            grip: "HORNS",
            reps: 8,
          },
          {
            id: "d6-swing",
            kind: "TIMED_MOVEMENT",
            exerciseId: "kb-swing",
            grip: "HANDLE",
            reps: 10,
          },
        ],
      },
      {
        id: "d6-s2",
        type: "STRAIGHT_SETS",
        title: "PUSH-UPS",
        intro: "Stop approximately 2 clean reps before failure.",
        prescriptions: [
          {
            id: "d6-pushup",
            kind: "SETS",
            exerciseId: "push-up",
            grip: "BODYWEIGHT",
            sets: 3,
            reps: "stop ~2 before failure",
          },
        ],
      },
      {
        id: "d6-s3",
        type: "STRAIGHT_SETS",
        title: "SUITCASE CARRY",
        prescriptions: [
          {
            id: "d6-carry",
            kind: "SETS",
            exerciseId: "suitcase-carry",
            grip: "HANDLE",
            sets: 3,
            durationSec: 30,
            perSide: true,
            weightKg: 24,
          },
        ],
      },
    ],
  },

  // ============================================================ DAY 7
  {
    day: 7,
    name: "REST / RECOVERY",
    intensity: "REST",
    emphasis: "SKILL",
    goal: "Recover. More training is useful only if recovery remains good.",
    quote: "Rest is part of the program.",
    isRest: true,
    restSuggestions: [
      "Walk",
      "Eat sufficient protein",
      "Sleep",
      "Light mobility if desired",
    ],
    sections: [],
  },
];

export function getDayTemplate(day: number): DayTemplate {
  const t = WEEK1.find((d) => d.day === day);
  if (!t) throw new Error(`No template for day ${day}`);
  return t;
}
